doc/developer-guide.md

Update GitHub repository URL to point to HTTPS version in developer guide.

---

Makefile

I had some trouble getting `make test` to run the tests, but got it working with some changes to the makefile:
- test/ADDONS -> test/addons
- add bin/ to path when running shelltest so hledgerdev is found
- use `cabal exec` to find shelltest in cabal sandbox
I think it makes sense why this is needed, if 
- you normally use a case-insensitive filesystem,
- you have hledgerdev in your path, and
- you don't install shalltest in a sandbox?
But I'm new to using Haskell so feel free to suggest better ways of fixing it!

Changes to make `make test` run

---

data/alias.journal
data/business.journal
data/personal.journal
doc/manual.md
hledger-lib/Hledger/Read.hs
hledger/Hledger/Cli/Main.hs
hledger/Hledger/Cli/Options.hs
hledger/Hledger/Cli/Utils.hs
tests/cli/alias.journal
tests/cli/business.journal
tests/cli/multiple-files.test
tests/cli/personal.journal

Fixes bug #165, though instead of `hledger inc -f file1 file2` it is `hledger inc -f file1 -f file2`: the former would interfere with specifying patterns on the command line.
Notes:
This did make the API slightly redundant, exporting both readJournalFiles and readJournalFile. (I have a version without readJournalFile, but the web frontend isn't tested.)
The first file is added to journalFilePaths with the contents of all the files and I haven't looked exhaustively for bugs that may cause, but I suspect it might only be parser error messages with the wrong file name. That looks like a problem to be solved along side the include file parsing one (hledger-lib/Hledger/Read/CsvReader.hs:812).
The important possible bug that I came up with was fine though: `hledger add -f file1 -f file2` …

handle multiple -f parameters sensibly

---

hledger-web/Handler/JournalR.hs
hledger-web/static/hledger.js

This error happens in Chrome and in Firefox too.
See pull request #251. 
The link 'Add a transaction' is working because it is triggered by bootstrap `data-toggle=modal data-target="#addmodal`. The keyboard follows another path because it resets the form before calling `modal` on `$("#addmodal")`.. that helped discover that the link 'Add a transaction' does not clean the form in fact. :)
Should I leave it like this? Should I clean the form after clicking 'Add transaction' ? I think the best would be:
- Put a link on the form (below the 'X') to clean the fields.
- (Possibly) do not clean the form when pressing 'a'.

hledger-web: Fixes keyboard shortcut for adding a transaction. 

---

hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Utils.hs
hledger/doc/examples.m4.md
hledger/doc/options.m4.md
tests/misc/pivot.test

Hey,
I found the --pivot from the original ledger to be very useful, so I reimplemented it for hledger. I am fairly new at haskell, so feel free to criticize my code in any way you can imagine. If you would like to include the feature in hledger I am open to modify the pull request according to your wishes.
The option --pivot TAG will change
2016/02/16 Test Transaction
Account1                                   2 EUR
Account2                                  -2 EUR
; TAG: value
to
2016/02/16 Test Transaction
Account1  2 EUR
TAG:value  -2 EUR
; TAG: value
while this run of hledger. (Node: This differs slightly from the original ledger, where --pivot will instead create the posting `TAG:value:Account2  -2 EUR`. One could consider renaming or offering both features.)
Greetings,
Malte

Add --pivot option

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UITypes.hs
hledger-ui/Hledger/UI/UIUtils.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml

The explicit exports are necessary to prevent ambiguity errors with `Mode` and `setMode` in `vty`. I have to admit that I didn’t get around to testing vty 0.6 (which was previously excluded by the bounds) but it works with vty 0.7.

Support vty 0.7

---

hledger-lib/Hledger/Data/Amount.hs

The haddocks for `amounts` are a bit broken, see [here](https://hackage.haskell.org/package/hledger-lib-0.27.1/docs/Hledger-Data-Amount.html#v:amounts).

fix the haddock for amounts

---

hledger-lib/Hledger/Read/CsvReader.hs

A single line containing `account1 ` (note the space at the end) should
parse as assignment of the empty string to account1. At least it did
until commit 4141067.
The problem is that megaparsec's `space` parses multiple space
characters as opposed to parsec. So in the example above it would
incorrectly consume the newline.

Fix csv rules parsing

---

.gitignore

This is the replacement for `dist` when using `cabal new-build`. Since I have started to use it for some things, I got annoyed by having a dirty `git status`.
If you want, I can also add a `cabal.project` which is similar to `stack.yaml` but doesn’t contain something like a resolver so even if you don’t use it, it shouldn’t require a lot of maintenance effort. 
I wanted to leave that decision separate from ignoring `dist-newstyle` (which I want to have either way) so I didn’t add the cabal.project directly.

Ignore dist-newstyle

---

.gitignore
cabal.project

I also snuck some ignores in there. `*~` is for backup files created by emacs and `cabal.project.local` contains *temporary* changes to things like ghc-options so it should never be commited.

Add a cabal.project file

---

hledger-web/Foundation.hs
hledger-web/Handler/Common.hs

By overriding the default brower-styles using the class `btn-default`, the buttons on hldeger-web are now rendered the same on all browsers. It also gives the interface a cleaner look

Added .btn-default to unify buttons across browsers

---

hledger-lib/Hledger/Read.hs

Changed behavior of `readJournalFiles` to be identical to `readJournalFile` for singleton lists

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Utils/Parse.hs
tests/cli/multiple-files.test

As a user of the library I was often unable to use the provided parsers outside of IO or ExceptT. This commit should not change to values, only generalize their types.

more general parser types enabling reuse outside of IO

---

hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/Hledger/Cli/Balancesheet.hs
hledger/Hledger/Cli/Cashflow.hs
hledger/Hledger/Cli/Incomestatement.hs
hledger/Hledger/Cli/Register.hs

Let me know if this is in the spirit of the library/utility! :)
I tried my best to adhere to the style that I saw used across the library, but feel free to tell me if there are any stylistic inconsistencies!
I see some potential for refactoring out balancesheet/incomestatement/cashflow commands, too, and would be willing to do it if you think that it'd be helpful to do so.

Adding "--value"/"-V" option for balancesheet/incomestatement/cashflow and register

---

hledger-lib/Hledger/Data/Transaction.hs
tests/journal/commodities.test

This fixes issue exposed by a fix for simonmichael/hledger#465
```
2016/1/1
saving-card  $-105
snacks  95 EUR @@ $100
Equity:Unbalanced  ; absence of $5 here triggers strange behavior
```
Before
```
2016/01/01
saving-card                 $-105
snacks             95 EUR @@ $100
Equity:Unbalanced            $105    ; absence of $5 here triggers strange behavior
Equity:Unbalanced           $-100    ; absence of $5 here triggers strange behavior
```
Now:
```
2016/01/01
saving-card                 $-105
snacks             95 EUR @@ $100
Equity:Unbalanced              $5    ; absence of $5 here triggers strange behavior
```

Normalize amount in infereBalancingAmount

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Utils.hs
hledger/Hledger/Cli/Register.hs

This is the result of applying Neil Mitchell’s trick of limiting the stack size to hledger.
Let me break down the different changes:
- `sum`, `maximum` and `minimum` use `foldl` instead of `foldl'` which can leak memory.
- Since `asprecision` is rarely evaluated this is responsible for another spaceleak.
- Lastly `sequence` is sort of a false positive so I mostly made the change here to be able to use the trick. Looking at [benchmarks](http://www.joachim-breitner.de/blog/684-Constructing_a_list_in_a_monad_revisited) it seems like this difference list based version is slightly faster on small lists but is slower on bigger lists.
Here are the benchmark results:
**before**
```
Benchmark bench: RUNNING...
Benchmarking hledger in /home/moritz/code/haskell/hledger/baseline/hledger with …
```

Fix a few spaceleaks

---

README.md

Now backers and sponsors from Open Collective will show up here automatically. 
More info [here](https://github.com/opencollective/opencollective/wiki/Github-banner)
[example](https://github.com/apex/apex#backers)

add backers&sponsors from Open Collective

---

bin/hledger-rewrite.hs
tests/bin/rewrite.test

Probably the most natural usage would be `hledger rewrite -f rewrites.hledger`. See tests for examples.
Currently no compatibility with C++ `ledger` expressions. Same for posting values. Commodity `*` is used to identify relative amounts to posting.
*Note*: users who migrated from C++ `ledger` probably want to move their automated transactions into a separate file to avoid unintentional rewrites. Maybe we should add option to control application of automated transactions from journal.

Apply ModifierTransaction's from journal during hledger-rewrite.

---

hledger-lib/Hledger/Reports/ReportOptions.hs

Megaparsec's show instance for ParseError doesn't produce digestible
strings. parseErrorPretty has to be used instead.

Prettify option parsing errors

---

bin/.gitignore
hledger-lib/Hledger/Data/Transaction.hs

```
HEAD is now at d657374a... doc: note an issue with balance assertions & multiple -f options
(pts/33/rxvt-unicode-256color) nikolay@ony [0]  2017-01-16 16:57:56
~/contrib/hledger
zsh% stack build --ghc-options=-O2 >& /dev/null && stack exec -- hledger -f examples/10000x1000x10.journal bal > /dev/null +RTS -s
3,115,009,192 bytes allocated in the heap
287,039,088 bytes copied during GC
37,426,776 bytes maximum residency (11 sample(s))
2,516,552 bytes maximum slop
105 MB total memory in use (0 MB lost due to fragmentation)
Tot time (elapsed)  Avg pause  Max pause
Gen  0      6013 colls,     0 par    0.211s   0.218s     0.0000s    0.0073s
Gen  1        11 colls,     0 par    0.108s   0.108s     0.0098s    0.0348s
TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)
SPARKS: 0 (0 …
```

txnTieKnot fix (~10% memory reduce)

---

hledger/Hledger/Cli/Utils.hs
tests/misc/pivot.test

Without this fix for postings without tag query checked effective account which is always empty text ("").

cli: fix bug in pivot for postings without tag

---

bin/hledger-rewrite.hs
hledger-lib/Hledger/Data/AutoTransaction.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Print.hs
hledger/Hledger/Cli/Utils.hs
hledger/doc/commands.m4.md
tests/bin/rewrite.test
tests/journal/balance-assertions.test
tests/misc/pivot.test

New option to `hledger-rewrite` to generate patch suitable for applying on original files.
Right now output of `hledger-rewrite` is just a one big journal. Everything except transaction is stripped. Transactions re-ordered. I guess most people wouldn't use it to rewrite their hand edited ledger journal for these reasons.
New output `hledger-rewrite --diff` produce only diff between an original text and the re-written transactions ignoring everything else. Benefits:
- Diff is suitable for feeding as input for `patch` tool. As result this allows updating some chunks of original files (multiple allowed).
- You can pass output through `colordiff` to see eye appealing demonstration of what re-write is going to perform.
```
Output:
--diff                         generate diff suitable as an …
```

Make hledger-rewrite tool suitable for re-factoring original journals

---

bin/.gitignore
bin/hledger-budget.hs
hledger-lib/Hledger/Data/AutoTransaction.hs
hledger/doc/commands.m4.md
tests/bin/budget.test

Until we'll get a better budgeting solution let's borrow one from C++ ledger approach.
- Modification transactions are active like in `hledger-rewrite`. If you like to fill budget buckets/envelopes manually.
- Periodic transactions inject `Budget transaction`s on a range of journal prepending any transaction in original journal. Can be disabled with `--no-offset` when you just need bucketing feature.
- Shrink tree of account to a smaller one according to account names used postings of periodic transactions.
Differences from C++ ledger:
- Posting match expression in modification transaction uses the syntax of queries of command-line.
- Period expression uses the syntax of `--period` option. I had to change keywords to lowercase.
- Order of postings in periodic transactions doesn't matter. …

Budgeting addon to simulate behavior of C++ ledger with option --budget

---

bin/.gitignore
bin/hledger-prices.hs
tests/bin/prices.test

I've created this one when I had to use pipeline of `hledger-rewrite` and `hledger` to resurrect prices from original journal. I tried this before I've got #485.
Still might be useful to report all know prices. Additionally option `--costs` gives ability to build prices from postings costs.

prices: new addon 

---

bin/hledger-equity.hs
tests/bin/equity.test

Helps to ensure that expectations for these transactions are met. I.e. there is no other postings in between or that an opening transaction is the first one in a journal.

equity: generate assertions

---

bin/hledger-check.hs

A script to check assertions over journals, at various levels of (time-based) granularity. Assertions aren't just balance assertions, but can also express relations between accounts. The documentation in the script has a couple of examples, here's another from my journal:
```
>>>  ./hledger-check.hs "assets:santander:main:budget:fun  >= £0"
assertion 'assets:santander:main:budget:fun  >= £0' violated
after transaction:
01/14 Steam via PayPal (EU4 Wealth of Nations expansion)
expenses:fun  £7.99
assets:santander:main:budget:fun
(after posting: 2017-01-19  as:sa:main:budget:fun      £-7.99  ;)
relevant balances:
assets:santander:main:budget:fun  £-5.24
```
Whoops, I thought I had more money left over than I did, and so had too much fun this month.

Add hledger-check script.

---

hledger-lib/Hledger/Data.hs
hledger-lib/Hledger/Data/MarketPrice.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml

Not too big a deal!  Not sure if it's worth an entire module.  Tried writing tests (parse and re-show), but couldn't get it to work cleanly without cyclic imports.
By the way, I noticed that hledger parses market price directives with "full" datetimes, but throws away the times.   Would it be worthwhile to modify the `MarketPrice` type to also include a full datetime, potentially, as well, if it was given one?

Added a simple 'showMarketPrice' function to show market price directives in a journal-compatible way

---

hledger/Hledger/Cli/Main.hs

I was working through the documentation, and this wouldn't work as-is. I noticed that there is an additional argument `assrt` which is not used here. Passing `True` causes this example to work.

Add missing assrt param to documentation.

---

hledger/Hledger/Cli/BalanceView.hs
hledger/Hledger/Cli/Balancesheet.hs
hledger/Hledger/Cli/Cashflow.hs
hledger/Hledger/Cli/Incomestatement.hs

for #514: is/cf are now properly period reports, and bs is a snapshot report.  period/snapshot mode is now a configuration flag for BalanceView

incomestatement / cashflow behavior bugfix

---

hledger/Hledger/Cli/Balance.hs

As discussed earlier, just a separate PR for getting rid of the warning in `Balance.hs`

fixed warnings in Balance.hs

---

hledger/Hledger/Cli/BalanceView.hs
hledger/doc/commands.m4.md

Unless I'm mistaken, the PR in its current statement fixes the issues mentioned in #518 and #525 .
1. `--average` for final total row is rendered properly, even in the absence of `--total`.
2. No final total column for multicolumn cashflow.  This means that cashflow essentially ignores `-N` in multicolumn mode.
3. Extra clarification is shown for titles in the case where an "unusual" balance report type is used for a given command.  For example, `--historical` for incomestatement properly indicates the type of statement being shown.  Only shows up when the mode is explicitly overridden.
4. `--historical` now works properly in simple single-column mode
5. documentation for bs/cf/is updated to reflect new changes in functionality.

Fixing ongoing issues in balance statement/income statement/cashflow

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/doc/hledger_csv.5.m4.md
tests/csv/read.test

Ability to add balance assertions in csv reader

"balance" parser for csv reader

---

site/download.md

I just adopted and updated the [Arch User Repository (AUR) package](https://aur.archlinux.org/packages/hledger/) so here we go :smile_cat:

Add Arch Linux to download page

---

hledger-lib/Hledger/Read/CsvReader.hs
tests/csv/read.test

It prevents hledger to crash later, as it fails to read
amount strings containing more than one '-'
Fix #524

CsvReader: simplify '-' signs if there exist more than one

---

Shake.hs

Use pandoc from stackage snapshot when building documentation to ensure
that pandoc and the pandoc filters are built against the same version of
pandoc-types; otherwise, the filters can fail with an obtuse error (see
https://github.com/jgm/pandoc/issues/3217).

Use pandoc From Stackage Snapshot

---

hledger-lib/doc/hledger_csv.5.m4.md

`#balance-assertions` anchor (added in 2ac77338f84be2b75157b9941d2230f598289212).

Fix trivial typo in CSV docs

---

bin/hledger-rewrite.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/AutoTransaction.hs
hledger-lib/Hledger/Data/Commodity.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
tests/bin/rewrite.test

When generating a new posting as a multiple of an existing posting,
support conversion to a different commodity.  For example, postings in
hours can be used to generate postings in USD.
Automatic transactions generated from rewrite rules use the commodity,
amount style, and transaction price if the rewrite defines a commodity.

Add Support for Rewriting Multipler Postings Into Different Commodities

---

doc/mockups/help.txt
hledger/Hledger/Cli/Main.hs

Documentation listed `---man` as the command to bring up the man pages instead of the correct `--man`

Fix typo in help docs

---

hledger/Hledger/Cli/BalanceView.hs

Should properly address #552, and also #565.  Looks like the issue was that I was trying to duplicate the code in `Balance.hs`, but did not duplicate the logic completely (left out an extra conditional).  Would be nice if all the code duplication doesn't have to be here...i'll try to see if there's a way to consolidate the two in the future.

Fixing bs/is/cf --flat regressions

---

hledger/Hledger/Cli/BalanceView.hs

Small patch, just changes to show the "total" field in bs/is/cf outputs in red if they are negative, using `cshowAmount` instead of `showAMount`.

Show colorized amounts for totals of bs/is/cf

---

bin/hledger-prices.hs
tests/bin/prices.test

- Precision is extended for inferred prices from division.
- Support for reverse price inference to support use cases when people bring money into transaction from account with non-main currency.
- Sort prices by dates.

prices: improve precision and add inverted costs

---

hledger-api/CHANGES
hledger-lib/CHANGES
hledger-ui/CHANGES
hledger-web/CHANGES
hledger/CHANGES

I feel a little silly making a small PR for this, but the date did throw me off when I was wondering if version 1.2 was recent or not.
Thanks for making `hledger` by the way! I use it all the time.

Fix date of 1.2 release in CHANGES files

---

site/download.md

`hledger` is is now part of Arch Linux [community] so it's now available directly from `pacman`

Update Arch Linux command

---

hledger-lib/Hledger/Data/Journal.hs
tests/cashflow/cashflow.test

Add "fixed" to the regex used to exclude asset accounts from cashflow
reports.  Assumes accounts are set up something like:
```
assets:fixed assets:equipment
assets:fixed assets:vehicles
assets:fixed assets:buildings
```

Exclude Fixed Assets from Cashflow Report

---

hledger/Hledger/Cli.hs
hledger/Hledger/Cli/Balancesheetequity.hs
hledger/Hledger/Cli/Main.hs
hledger/hledger.cabal
hledger/package.yaml

This is only a small demonstration to see the incidence of adding the default equity account to the balance sheet report.

Staging commit: This is only to demonstrate balance sheet with equity.

---

hledger-ui/Hledger/UI/Main.hs
hledger-web/Hledger/Web/Main.hs
hledger/Hledger/Cli/Utils.hs

This is a very simple change, fixing #474.
I've exposed pivot and anon from Cli.Utils and used them in the custom withJournalDo that -ui and -web have. Other tools can already use --pivot and --anon (at least the tools in /bin), as they use the withJournalDo from Cli.Utils (either directly or using a wrapper, as hledger-budger does).
Though I'd suggest changing the signature of withJournalDo to `CliOpts -> (Journal -> IO ()) -> IO ()` and partially applying the whole UiOpts/WebOpts, so that there can be one unified withJournalDo.
(I haven't done that now, as that changes the API and requires more changes.)

ui, web: Enable --pivot and --anon in ui and web (#474)

---

hledger-web/Handler/JournalR.hs

This fixes the rest of #430.
Adding a href to an anchor makes it into a button, adding it into the tab order and making it clickable. While having data-toggle="modal" adds JS onclick to the link, making it clickable, it is adding href="#" that makes it selectable via tab and clickable via space.

web: Make "Add transaction" button tabbable (#430)

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Transaction.hs
tests/journal/balance-assertions.test

Addresses #481.
This works, but I'm very new to Haskell and I'm not sure I'm breaking any rules or best practices. Please let me know if there's a better way to do anything, especially where I'm increasing the `GenericSourcePos`'s line number.
Also, this currently prints column 0. Should we try for a custom message instead?

Balance assertion errors now show line of failed assertion posting.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger/Hledger/Cli/Commands/Equity.hs
tests/journal/balance-assertions.test

Addresses further concerns in #481 regarding column number.
I changed the BalanceAssertion type such that it now tracks the line number and column of the balance assertion's `=`. I changed all references to BalanceAssertions to reflect this.
I removed the previous code for finding the line number, as it was no longer required.
Changed test to also check column number.

Rewrite of BalanceAssertion type to track its source position.

---

README.md

An update to GitHub's markdown parser made it so a space is required between hash characters and the text of titles for them to be displayed correctly.

doc: fix readme markdown formatting on github

---

hledger-lib/Hledger/Data/AutoTransaction.hs
hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Utils/Parse.hs

- Simplify ~and make more strict~ doctests for periodexpr.
- ~Test that expose backtracking issue. Borrowed from simonmichael/hledger#654 .~
- Besides consuming leading space consume ending space for periodexpr also.
- Drop implicit option (def, def) behaviour of periodexpr. I.e. disallow hledger reg -p '' and auto-transaction with heading just '~'.
- Slightly re-factor periodexpr.
- _Ensure that reportinginterval doesn't consume trailing space. Useful if  we'll start disallowing periods like "every1stjan2009-"._

Fix backtracking in periodexpr parser

---

hledger-lib/Hledger/Read/JournalReader.hs
tests/journal/directives.test

- Factor out `wordsp`.
- Limit scope of directives backtracking.
Resolves simonmichael/hledger#402

Improve error reporting for directives

---

bin/hledger-check.hs

Fix build error for `hledger-check` external addon that have no compatibility with older versions of `megaparsec`.
When built with `stack8.0.yaml` included in `hledger`:
```
[1 of 1] Compiling Main             ( hledger-check.hs, hledger-check.o )
hledger-check.hs:474:44: error:
• Couldn't match type ‘Data.Text.Internal.Text’ with ‘[Char]’
Expected type: String
Actual type: Data.Text.Internal.Text
• In the first argument of ‘P.string’, namely ‘(pack s)’
In the first argument of ‘(*>)’, namely ‘P.string (pack s)’
In the first argument of ‘P.try’, namely
‘(P.string (pack s) *> pure a)’
```

hledger-check: compatibility with stack8.0.yaml

---

hledger/Hledger/Cli/Commands/Balance.hs
tests/budget/budget.test

For multi-column balance report, if there are no transactions in the
given period for budgeted account, display [0% of <budget>] for
consistency.
If balance is a mix of commodities, convert to cost basis for the
purposes of computing percent of balance spent.

lib: fix budget display to always display percent consumed and handle costs

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read/JournalReader.hs

- Small additional fix for issue spot by @dashed in #487 to inherit effect of `commodity` directive on parsing included files.
- Fix style canonicalization when `--cost` option applied ( #509 ).
- Get pretty error report for included journals ( #660 ).

Small fixes to journal handling (styles, error, commodity scope)

---

.gitignore
site/download.md

Add the `--no-nix-pure` flag to forward environment variables.
Without this flag the build fails.

Docs: Nix Stack build note.

---

stack.yaml

Resolves #668, possibly #669.
I was able to successfully build master using this `stack.yaml` and running the following:
```
$ stack --nix --no-nix-pure install
```
The `nix-no-pure` preserves `LANG` and other user environment variables so the documentation files will build successfully. It may be a better nix practice to use a `shell.nix` as outlined [here](https://docs.haskellstack.org/en/stable/nix_integration/) to set the `LANG` explicitly. An example file is [here](https://github.com/aelve/guide/blob/master/shell.nix)

specify nix integration options in stack.yaml

---

stack.yaml

Current lts includes last ghc version and hledger builds ok with it

stack: bump default resolver to lts-10.0

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/doc/hledger_journal.5.m4.md
tests/journal/numbers.test

Note that this pull request shares some common history with #635, but still can go independently.
Resolves #330

Allow to use space as a digit groups separator

---

.travis.yml

This should hopefully fix the following Travis CI build error:
```
fatal: unable to access 'http://github.com/simonmichael/shelltestrunner/': Failed to connect to github.com port 443: Connection timed out
```
(see https://travis-ci.org/simonmichael/hledger/jobs/323972730#L487 )

Clone from github over https

---

hledger-web/hledger-web.m4.md
site/doc/1.5/hledger-ui.md
site/doc/1.5/hledger-web.md

Alrighty, this should actually fix #692.  I actually verified it locally this time by running `make site-preview` :smile: 
Saw it here as well: http://hledger.org/hledger-ui.html
saw the `:::` macro in hledger-web, hledger-ui so removed. Not sure if
that had special behavior in somewhere in the build chain. Is this some kind of hakyll syntax?

doc: remove raw markup macro

---

stack.yaml

Fix #712 
I tested this on Arch Linux + a nix install and it does use nix for the stack installation when have mentioned config in my `~/.stack/config.yaml`.
@cdepillabout would you mind testing this on NixOS?
Thanks for the improvement too!

ensure stack's nix config works on nixos

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Utils/String.hs
hledger/Hledger/Cli/Commands/Add.hs

Using `many` and `some` only to then ignore the result will still allocate the list of characters. By using `skipMany/skipSome` we can avoid this and thereby slightly reduce memory allocations.
The gains are sadly not particularly large but running a balance report with `+RTS -s` shows a decrease in total bytes allocated as well as max residency (and also a minor improvement in runtime performance but that’s probably too small to be significant):
Old:
```
650,905,632 bytes allocated in the heap
74,621,888 bytes copied during GC
9,646,752 bytes maximum residency (9 sample(s))
64,864 bytes maximum slop
29 MB total memory in use (0 MB lost due to fragmentation)
```
New:
```
646,328,488 bytes allocated in the heap
73,869,168 bytes copied during GC
9,375,360 bytes maximum residency (9 …
```

Use skipMany/skipSome for parsing spacenonewline

---

hledger-lib/Hledger/Read/CsvReader.hs

I had issues debugging why my CSV reading file wasn't working.
Actually printing out the amount-in and amount-out helped me debug my issues.
I've also included some error message formatting changes.

CsvReader: print more information about amount-in/out errors

---

dev.hs
hledger-api/hledger-api.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-ui/Hledger/UI/Main.hs
hledger-web/Application.hs
hledger-web/Handler/EditForm.hs
hledger-web/Hledger/Web/Main.hs
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Import.hs
hledger/Hledger/Cli/Main.hs
hledger/Hledger/Cli/Utils.hs
hledger/bench/bench.hs

Same for tryReader[s]WithOpts -> tryReader[s]
Remove InputOpts-less versions of tryReader and readJournal as they are unused.

lib, app, web, ui: rename readJournalFile[s]WithOpts to readJournalFile

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-ui/Hledger/UI/Main.hs
hledger-web/Hledger/Web/Main.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Utils.hs
tests/misc/account-aliases.test

Commandline aliases are injected into parser state at the beginning of parsing, making them behave exactly the same way as if they were written at the top of the file. Aliases would now affect transactions
prior to amount inference and balance checks, which should fix #730

Treat commandline aliases same way as file aliases

---

hledger-lib/Hledger/Data/AutoTransaction.hs
hledger/Hledger/Cli/Utils.hs
tests/budget/forecast.test

Include period in the description of generated forecast transaction. I think that this greatly improves the output of "print" and "register" with --forecast.

lib, app: better descriptions for forecast transactions

---

site/hakyll-std/TableOfContents.hs
site/hakyll-std/hakyll-std.hs

This fixes a few issues with the files in `site/hakyll-std` regarding the updates that happenned to Pandoc.
Basically, pandoc decided to monadify-everything, which means we need to build the document using `runPure`.
Additionally, `unpack` needs to be called inside the `fromMaybe` so that both arguments are of type `String`.
I think ideally this file would be phased out.
These fixes need to get in before https://github.com/simonmichael/hledger/issues/670 can make progress.

Pandoc 2 fixes

---

hledger-lib/Hledger/Read/Common.hs

In commit 30ae9914, I introduced a performance regression: the memory usage of `hledger -f examples/10000x10000x10.journal register +RTS -s > /dev/null` (compiled with `-O2`) increased from `92 MB` to `104 MB`. The change contained in this pull request reverses the regression when applied to both 30ae9914 and the current master branch.

lib: fix performance regression introduced in 30ae9914

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs

In this PR I refactor the comment parsers (in `Hledger/Read`).
I have done this to prepare for a discussion and potential implementation of changes to the allowed syntax for comments, tags, date-tags, and bracketed dates. The intention of this PR, however, is to preserve the current syntax and behaviour.
The primary refactoring in this PR, taking place in the first four commits, is the weakening of several parsers from `ErroringJournalParser` (`StateT Journal`, `ParsecT`, and `ExceptT`) or `JournalParser` (`StateT Journal`, `ParsecT`) to `SimpleTextParser` (`Parsec`). From brief checks (`+RTS s`), this change is associated with a slight decrease in performance (slightly longer runtime, slightly higher memory usage when parsing comments). This is surprising to me, as I was expecting these …

Refactor comment parsers

---

hledger-lib/Hledger/Read/Common.hs
tests/journal/amounts-and-commodities.test

This PR addresses a problem which was found in issue #749. This PR does not address that issue.
The problem was that we fail to parse the following journal
```
commodity 1 000  USD
2018-01-01
(a)   USD1 000
```
failing with the following error
```
hledger: test.journal:1:12:
unexpected space
expecting digit
```
We fail to parse this next journal as well
```
2018-01-01
(a)   USD1 000 ; comment
```
```
hledger: test2.journal:2:9:
unexpected 'U'
expecting '=', '{', end of input, or newline
```
It seems that the issue is caused by the use of a space as the digits separator and trailing whitespace after the amount. The current parser consumes the trailing whitespace as a separator and then expects at least another digit, which it does not find. This patch groups together the separator and the …

lib: fix parsing of amounts with a whitespace digits separator 

---

hledger-lib/Hledger/Read/Common.hs
tests/journal/amounts-and-commodities.test

This PR fixes #749 by implementing the changes discussed therein. That is, we ensure that a whitespace character is never used as a decimal point.
This PR also enables the tests that were prepared for issue #749.

lib: fix issue where spaces were allowed as decimal points

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
tests/journal/dates.test
tests/journal/posting-dates.test

I have been working on rewriting and refactoring the parsers in `/hledger-lib/Hledger/Read/Common.hs`. I have tried to make it easier to follow the logic of the parsers by adding more structure, but this also makes the code more verbose. So, I'm not entirely sure that these rewrites represent an improvement, and I would appreciate feedback.
This PR:
- Rewrites the date parser `datep`. This changes the method of parsing, and hence the way in which the parser fails and also the error messages. I have modified some of the date parsing tests to accomodate these changes.
- Rewrites the raw number parser `rawnumberp` and `fromRawNumber`. I have added two new types, `DigitGrp` and `RawNumber`, to give more structure to this parser. `DigitGrp` replaces `String` as a more efficient representation …

Rewriting and refactoring parsers (WIP)

---

hledger-lib/Hledger/Read/Common.hs

I've done some more work to refactor and touch up the parser, continuing the work in the last pull request.
This pull request:
- Refactors the parsing of signs (for numbers) and extracts the handling of signs out of `fromRawNumber`. My rationale for this is that the sign can be applied independently of the logic in `fromRawNumber`.
- Refactors the raw number parser (again) in an attempt to reduce the verbosity introduced in the last pull request. I have split off the `AmbiguousNumber` constructor of `RawNumber` into its own type, and introduced a function `AmbiguousNumber -> RawNumber` explicitly capturing the disambiguation logic. I have also reduced the number of remaining constructors in `RawNumber` to just two, distinguishing whether a raw number has digit separators or not. My …

More work on the parser

---

hledger-ui/Hledger/UI/Editor.hs

When neovim is set as EDITOR hleger will jump to the correct line number of the transaction; before hledger will open journal at top of the file

feat(hledger-ui): added neovim as a supported editor

---

Makefile

This allows to simply add `--nix` to the topmost `STACK=stack` assignment in order to get things to build on NixOS.

travis: use STACK variable

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/StringFormat.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
hledger-web/hledger-web.cabal
hledger-web/package.yaml
hledger/hledger.cabal
hledger/package.yaml
stack.yaml

We don't need to import Data.Monoid because Prelude.Compat exports "<>"
already. In fact, importing that module causes build failures:
Hledger/Read/Common.hs:725:62: error:
Ambiguous occurrence ‘<>’
It could refer to either ‘Sem.<>’,
imported from ‘Prelude.Compat’ at Hledger/Read/Common.hs:97:1-39
(and originally defined in ‘Data.Semigroup’)
or ‘Data.Monoid.<>’,
imported from ‘Data.Monoid’ at Hledger/Read/Common.hs:110:1-18
Fixes https://github.com/simonmichael/hledger/issues/794.

Fix hledger-lib build with ghc 8.0.x and base-compat 0.10.x.

---

hledger-lib/tests/doctests.hs

Added the `--fast` flag to the doctest call. Benchmarks from my macbook pro below.
Execution time with `--fast`:
```
❯ bash -c "time make doctest"
hledger-lib-1.9.99: test (suite: doctests)
Examples: 179  Tried: 179  Errors: 0  Failures: 0
hledger-lib-1.9.99: Test suite doctests passed
doctest PASSED
real    0m13.432s
user    0m11.193s
sys     0m1.582s
```
Execution time without `--fast`:
```
❯ bash -c "time make doctest"
hledger-lib-1.9.99: test (suite: doctests)
Examples: 179  Tried: 179  Errors: 0  Failures: 0
hledger-lib-1.9.99: Test suite doctests passed
doctest PASSED
real    0m23.741s
user    0m15.847s
sys     0m4.872s
```
Fixes #802

Add fast flag to doctests.

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger-lib/Hledger/Utils/ParseErrors.hs
hledger-lib/Text/Megaparsec/Custom.hs
hledger-lib/hledger-lib.cabal
hledger/Hledger/Cli/Commands/Rewrite.hs
tests/journal/parse-errors.test
tests/journal/posting-dates.test

This PR works towards improving the error messages in hledger by displaying the line of source on which a parse error occured. This was done by (1) embedding the source positions and the source itself into megaparsec's custom error type, and (2) by using megaparsec's `parseErrorPretty'` function, which was modified to suit our needs. 
In order to ensure that all parse errors go through megaparsec's machinery, this PR removes the `ExceptT String` layer of the parser and the `ErroringJournalParser` type. This required a rewrite/refactoring of the comment parsers and of the `includedirectivep` parser. (Unfortunately, the new comment parsers are slightly slower and use slightly more memory.)
In order to show an example parse error, one of the last commits refines the date parser, producing …

Display the line on which a parse error occurs

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs

This PR aims to improve the parse errors for parsers in `hledger-lib/Hledger/Read/Common.hs`
I'm not yet sure how best to improve the parse errors, so these changes might be considered a work in progress. I've basically tried to minimize the backtracking of the parsers and to write out more descriptive labels and error messages.
---
This PR contains one breaking change: in an amount, the multiplier symbol `*` must now always preceed the negative sign `-`. Before the changes, the multiplier came after the sign in `leftsymbolamountp`, whereas the sign came before the multiplier in `rightsymbolamountp` and `nosymbolamountp`. This PR factors out the parsing of the multipliers and signs from these three parsers into a single parser under `amountwithoutpricep` (in order to reduce backtracking), …

Improving parse errors

---

hledger-install/hledger-install.sh

This install script failed on my laptop. My OS is ubuntu 18.04.
I found the problem is `cmd_version xxxx` like `cmd_version hledger` will return empty string if
hledger is not installed, and then `cmpver $(cmd_version hledger) $HLEDGER_VERSION`
will become `cmpver $HLEDGER_VERSION`, and then `$(cmpver "$(cmd_version hledger)" $HLEDGER_VERSION) = 2` will be false.
Wrapping `$(cmd_version xxxx)` with double quotes can solve this, and it succeeds on my machine.
Trailing white spaces are trimmed automatically by my editor

Wrap $(cmd_version xxxx) with double quotes to solve installation failure

---

hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/hledger-lib.cabal
hledger-lib/hledger_journal.5
hledger-lib/hledger_journal.info
hledger-lib/hledger_journal.m4.md
hledger-lib/hledger_journal.txt
hledger-lib/package.yaml
tests/journal/include.test

Closes #843 and #303.
I am opening this as a "work in progress" to make sure I am on the right path, and get some feedback (especially on style)
+ ~~All the functional tests pass, however it seems that the doctests are failing. The root cause is that the `Glob` and `filemanip` packages both export modules called `System.FilePath.Glob`, and doctest does not know how to deal with this. I am a Haskell noob, so I am unsure how to proceed.~~
+ ~~Do we care that this change may potentially break existing journal files? Notably journal files that have filenames that are also valid glob patterns. IMO this does not seem relevant, but I wanted to bring it up.~~
+ Currently we are setting/resetting the parser state inside `parseChild`. Should this be factored out to the call site instead?
+ We are …

allow glob patterns in 'include' directive

---

hledger/Hledger/Cli/DocFiles.hs

Embedded files are now assumed to be UTF-8 independently of the system locale. This also replaces the file-embed dependency with `Hledger.Cli.TH`, where `embedStringFile` has been changed to assume UTF-8 (`utf8_bom`).
Compilation without a locale (e.g. in `nix-shell --pure` or `docker run -it fedora:28 bash` as @talex5 mentioned) now works without a problem.
~~I've also changed the `nix:` sections of `stack.yaml`s to use pure nix shells, and added the required dependencies of happy/alex - `stack build --nix` works for all build configs. (I'm on NixOS, so I can't actually develop without `--nix`, and compiling in a pure shell is also a nice bonus.)~~
Fixes #420, #813. ~~This is also a better solution to the closed #669.~~

cli: Fix compilation without LANG/LC_ALL set

---

hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Files.hs
hledger/hledger_commands.m4.md
hledger/package.yaml

This adds "hledger includes" that will list all included files.
This is useful for auditing and automation (I plan to build some Shake rules around rebuilding included files from CSV's)

cli: command to list included files

---

hledger-lib/Hledger/Data/Amount.hs
tests/budget/budget.test

This fixes #862 
I thnk that `amountValue` should not transplant original price of the amount into the amount value, as this will incorrectly inflate amount further down the line whenever `amountValue` of `costOfAmount` is applied on the result.
Fix is verified using sample from #862

lib: fix balance --budget in the presence of --value

---

hledger/Hledger/Cli/Utils.hs

I took another look at #878 and figured out that the reason why the balancesheet doesn’t just show zeros is that the original postings are present for inferred postings and are not anonymized. That causes the query to match for all postings with inferred amounts. By also anonymizing the original posting we now get zeros as expected and we avoid accidentally leaking information (the problem probably isn’t limited to balancesheet queries).

Anonymize original postings

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read/Common.hs
tests/budget/auto.test

This solves #893 by having `journalFinalise` run twice with automated transactions: the first run takes care of reordering and inferring amounts (but does not check assertions), the second does not reorder. It was necessary to make reordering a boolean flag in `journalFinalise`. Note that if `--auto` is not specified, the finalization is only run one time, as before.

Make transaction modifiers work correctly with inferred amounts

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read/Common.hs

This finishes removing `journalFinalise`, and adds a fix in the order of operations.
[Followon from [#893](https://github.com/simonmichael/hledger/pull/893), [#900](https://github.com/simonmichael/hledger/pull/900)]

Finish removing journalFinalise

---

cabal.project

These packages work fine with the latest version of their dependencies.
They just don't say so on Hackage.

disregard over-specified version constraints in brick and config-ini

---

site/site.tmpl

Fixes incorrectly indented code block issue (#816) by removing all indentation from `body`.
This does also make the generated HTML uglier.

Fix incorrectly indented code blocks in web manuals

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Text/Megaparsec/Custom.hs
hledger-lib/hledger_journal.m4.md
tests/budget/forecast.test

This PR re-implements a subset of PR #823 on top of the current codebase, specifically for addressing issues raised in PR #807.
In particular, the failing examples in https://github.com/simonmichael/hledger/pull/807#issuecomment-396994403 now work properly.

Add a custom parse error for "re-parsing"

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils/Test.hs
hledger-lib/hledger_journal.m4.md
hledger/Hledger/Cli/Commands/Accounts.hs

Account directives can now have comments and tags. Account types can be declared with a `type:` tag, and the account type syntax introduced in hledger 1.12 is deprecated (I guess ?). Docs have been improved. Account tags are not used for anything else (eg queries) yet.
Previous discussion: #877

allow account comments, tags, account types declared with tags

---

hledger/Hledger/Cli/Commands/Roi.hs
tests/misc/roi.test

Fixes #937 
When return on investment is very small, numerical solvers can jump around zero, sometimes producing very small negative numbers. Let's show everything smaller than 0.01% as 0%

cli: if abs(return on investment)<0.01% display it as zero

---

hledger/Hledger/Cli/Utils.hs
tests/print/auto.test

This fixes #953 by applying transaction modifiers to generated forecast transactions, if any

lib: make --auto work on --forecast transactions

---

hledger-install/hledger-install.sh

Function in hledger-install.sh that does version checks runs binaries without giving full path to them, so freshly-installed "stack" will fail version check if ~/.local/bin is not in PATH.
This could be fixed by moving PATH modification a bit up, before stack check/installation.

install: fix "stack" installation when .local/bin is not in PATH

---

hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Commands/Register.md

[Related to #307.]
Open questions:
- Can we introduce a shorthand for `--invert`? I'd prefer `-v` like in grep. `-i` often stands for in-place or ignore. `-v` would be available in balance and register.
- Do we better apply the `amt:` filter before or after negating the amounts? In balance, `--invert` seems to be applied only the the printed output, so after all filters. I think we should keep the meaning of `--invert` to only apply to the output.
And I don't understand the line
```
newtype MixedAmount = Mixed [Amount] deriving ...
```
Why are there multiple amounts possible for one posting and what is `Mixed`?

Support register --invert option to negate amounts

---

hledger/Hledger/Cli/Commands/Registermatch.hs

As discussed in #956 , just the `[QUERY]` in the usage text was wrong. It must be `DESC` (part of a description text) and it must be not optional.

Fix CLI help text

---

hledger-web/Hledger/Web/Handler/AddR.hs
hledger-web/Hledger/Web/Widget/AddForm.hs
hledger-web/templates/add-form.hamlet

Fixes #951.
The main purpose of this PR is just adding a `balanceTransaction Nothing txn`
validation, but I've also taken the liberty of cleaning up the mess I'd made in
add form validation half a year ago.
I've tried to rework the basic algorithm two or three times but I had to leave
it at an `unfoldr` as that was the only version that could account for all
corner cases. So instead I've restructured the rest of the code and added
comments and type annotations in hope of making the code in AddForm.hs more
accessible even to casual readers.

web: Re-add 'balanced transaction' validation to add form

---

hledger-ui/Hledger/UI/Main.hs
hledger-web/Hledger/Web/Main.hs
hledger/Hledger/Cli/Main.hs
hledger/Hledger/Cli/Utils.hs

This finally removes the duplication between hledger-cli's, hledger-ui's and
hledger-web's entrypoints. I'd wanted to do this a long time ago, but only now
was I annoyed enough by the XXX's around those places to actually do it :)
On another note, this PR conflicts with my other one (#978). I didn't want to
create a PR against another PR, so whichever one you get around to merging
first, I'll just need to rebase the other one (for the three lines of worth of
conflicts, oh well).
There is just one thing I'm not sure about. The original hledger-ui's entrypoint
did some changes to `CLIOpts` that I've pulled out so that they are now sent to
both `withJournalDo` and to `runBrickUI`, which wasn't the case previously as
`runBrickUi` used the unchanged `UIOpts`. The two options affected are …

cli, web, ui: Replace withJournalDo* variants

---

hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Diff.hs
hledger/Hledger/Cli/Commands/Diff.md
hledger/Hledger/Cli/Commands/Diff.txt
hledger/hledger.cabal
hledger/package.yaml

This PR merges the external [hledger-diff](https://github.com/gebner/hledger-diff) tool.  See https://github.com/gebner/hledger-diff/issues/8
I hope I've got the `Diff.txt` and `Diff.md` files right.

Merge hledger-diff as a cli command

---

Dockerfile
site/download.md

Dockerfile: use haskell as a base layer for faster build (stack, ghc preinstalled)
docs: mention the option of docker build from sources

Docker build : small fixes and docs

---

hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/hledger.cabal
hledger/package.yaml

This constraints the easytest dependency to <0.3, because hledger and
hledger-lib currently don't build with 0.3.
Of course the better solution would be to fix the build errors, but easytest-0.3
is not even in stackage nightly yet and I just need it to build right now :-)

Constrain easytest dependency to fix cabal build

---

doc/common.m4

I believe that this will fix the broken link under `--auto` in the options https://hledger.org/manual.html#options. The new link https://hledger.org/journal.html#auto-postings-transaction-modifiers seems to work; current link https://hledger.org/journal.html#automated-posting-rules does not.

fix link to auto postings

---

site/index.md

I've finally gotten round to giving `hledger-makeitso` a more serious name (as mentioned on the mailing list).
This PR just changes the name and the link to `hledger-flow`.
I see there is a similar link on https://plaintextaccounting.org/
I'll submit another PR on https://github.com/plaintextaccounting/plaintextaccounting.github.io
Are there any other places that needs updating?

Rename hledger-makeitso to hledger-flow

---

doc/mockups/entry-macros.txt
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/hledger_journal.5
hledger-lib/hledger_journal.info
hledger-lib/hledger_journal.m4.md
hledger-lib/hledger_journal.txt
tests/csv/csv-read.test
tests/i18n/wide-char-layout.test
tests/journal/auto-postings.test
tests/journal/comments.test
tests/journal/tags.test
tests/misc/amount-rendering.test
tests/misc/rewrite.test

print: differentiate line indent (4spc) from pre-comment space (2spc)

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/hledger_journal.m4.md
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Descriptions.hs
hledger/Hledger/Cli/Commands/Descriptions.md
hledger/Hledger/Cli/Commands/Descriptions.txt
hledger/Hledger/Cli/Commands/Notes.hs
hledger/Hledger/Cli/Commands/Notes.md
hledger/Hledger/Cli/Commands/Notes.txt
hledger/Hledger/Cli/Commands/Payees.hs
hledger/Hledger/Cli/Commands/Payees.md
hledger/Hledger/Cli/Commands/Payees.txt
hledger/hledger.cabal
hledger/package.yaml
tests/descriptions.test
tests/notes.test
tests/payees.test

This stuff is to fix #1062. Feel free to contribute ;-)

Add payees command

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Reports/BudgetReport.hs

This fixes #1085 
runPeriodicTransaction tried really hard to avoid generating all instances of periodic transaction since specified start date, trying instead to figure out closest start date before the requested span. Turns out that this is hard, and all attempts done so far (two of them by me) failed on some corner case or other.
Lets make it right, and then see if we need to make it fast :) If we generate all instances of transaction from its start date and up to the end of reporting interval, and then only take those that fall inside reporting interval, code becomes refreshingly simple :)
I added some tests from #1085 and commit 129f6e6839db91fb17c13aa9ce0718f168b5a193

Fix periodictxn generation

---

hledger-web/Hledger/Web/Application.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger-web/hledger-web.cabal
hledger-web/package.yaml

This PR adds a `--cors` option to the hledger-web command, which enables a simple CORS policy: it returns the `Access-Control-Allow-Origin: *` HTTP header.
The implementation was proposed by @MisterY in #1031. I just added the management of the CLI option.
Please, review thoroughly as this is my first ever PR in a Haskell project.
Fixes #1031.

Allow CORS to be enabled in hledger-web

---

hledger-install/hledger-install.sh

All three results in "git grep resolver | grep 14" now say 14.4.

Make resolver in hledger-install.sh consistent with that in stack.yaml

---

CONTRIBUTING.md

https://github.com/simonmichael/hledger/blob/master/CONTRIBUTING.md and https://hledger.org/CONTRIBUTING.html were displaying [[...]] literals

Fix internal Markdown links in CONTRIBUTING.md

---

hledger-lib/Hledger/Data/RawOptions.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/Main.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Import.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/Hledger/Cli/Commands/Tags.hs
tests/cli/date-options.test

It looks like we only need quote when we build query and in some
messages.
Fixes simonmichael/hledger#1079
_(here was big a banner)_

;lib: store raw opts unquoted

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Utils/String.hs
hledger-lib/hledger_csv.m4.md
tests/csv.test
tests/hledger-csv

Let's fix some outstanding CSV issues. This PR fixes:
- #841 and #416 : newlines in description/comment/precomment/... are not breaking output
- #570 : zero amount-in and non-zero amount-out (or vice versa) is no longer an error
- #500 : recursive interpolation works for all fields, including amount
- #1000: it is possible to use just balance assertions when reading csv
- #1001: empty field assignments are possible now
- #1076: it is now possible to write "if" expressions with "skip" in the body that will skip records
- #627 : csv rules could produce up to 9 postings, with different comments, balance assertions or currencies for each.
Obviously, the biggest change is multi-postings generation. I tried to streamline the code, so hopefully this bit is not too hard to read. 
Parser now …

Csv fixes mega pack 2019

---

hledger-lib/Hledger/Read/CsvReader.hs
tests/csv.test

This implements a suggestion from #1000: balance assertion style in CSV reader is now fully configurable

lib: csv reader gets balance-style directive

---

hledger-lib/Hledger/Data/RawOptions.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils.hs
hledger-lib/Hledger/Utils/UTF8IOCompat.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/UIOptions.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/Hledger/Cli/Main.hs

This was triggered by hardships of addressing #1104 .
- Hide `RawOpts` so no one can mess with it other than using `RawOptions` module.
- Remove obsolete `decodeRawOpts` and `SystemString`.
- Factor out few common ways of accessing `RawOpts` to `choiceopt` and `collectopts` in `RawOptions`.
With these changes confirmed that we use quotes only to build query string.
_(here was a big banner)_

Tiny re-factor RawOpts to hide internal representation

---

hledger-lib/Hledger/Data/RawOptions.hs

Use a work-around described in https://github.com/sol/hpack/issues/188 .
Unfortunately for `easytests` this produces ugly warning `-Wmissing-home-modules` ~~that I simply don't understand since the only difference between `doctests` and `easytests` is that last one include `hledger-lib` in dependencies to build simple CLI that is equivalent to `hledger test`~~.  
I had to use work-around to ensure that Cabal understand that we want to get `tests_Hledger` via library that we built.

re-enable doctests and easytests

---

hledger/Hledger/Cli/Commands/Checkdates.hs

Currently check-dates doesn't send a proper exist status.
This means we cannot rely on the status for automatic checks. For example
PR wraps the output of the command with the needed status codes.

Add exit status code to check-dates

---

README.md

Fixes #1141
It looks like the subdomain links do not quite work, hence replacing them with the links to the Travis and AppVeyor links.

Fix build badges for Travis and AppVeyor

---

examples/csv/csb43.csv
examples/csv/csb43.csv.rules

csb2format deals with the CSB43/AEB43 format, which all banks operating in
Spain must support.
Having these example rules enables easens bootstraping for users with a
Spanish bank account.

Add a basic example of rule parsing for the output of csb2format.

---

hledger-lib/Hledger/Utils/String.hs
tests/addons/addons.test
tests/rewrite.test

This PR attemts to fix #457.
It contains 2 commits:
+ The first commit adds four shelltests demonstrating the problem. I am not sure what the best place is for these tests to live. Please advise.
+ The second commit solves the problem by using existing machinery (`String.quoteIfNeeded`) to quote arguments which contain the characters which seem to be causing the problem: `<` and `>`. While ad-hoc experiments on the command line suggest that this solution fixes the problem, the tests added in the first commit continue to fail. I'm guessing that this might be related to the extra level of quoting that `shelltest` injects.

fix parsing of < and > in add-on commands (#457)

---

hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Add.md
hledger/Hledger/Cli/Commands/Add.txt
hledger/hledger.1
hledger/hledger.info
hledger/hledger.txt

This PR changes the `confirmedTransactionWizard` function to accept a list that is used as a stack to store the stages of the addition command so that the back command can go back to the right stage.
Is this a good approach towards implementing a back command for `add`?
Closes #577

Change the '<' command to go back one step during addition

---

tests/journal/auto-postings.test

Happy new year!
Since my PR #1159 failed (pure documentation) I checked what the problem was. Unfortunately, I don't really have a way of interpolating the current year in the result, so I figured adjusting the year manually would at least make the tests pass again!

Fix auto postings test.

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Ledger.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs

Previously, `multiBalanceReportWith` had been calculating the date of each posting once for every column. This resulted in quite significant slowdown when calculating for many postings and many `DateSpans`. This commit calculates the posting date of each posting only once and re-uses it. It also calculates the columns for each posting rather than searching through the whole colspan list every time.

Only calculate posting date once for each posting.

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Use PeriodicReport for MultiBalanceReport, and a new datatype for BalanceReport, to ease readability and reduce reliance on anonymous tuples. Also generalise PeriodicReport to allow for different labels than the usual (AccountName, AccountName).

Increase use of PeriodicReport

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

I think this cleans up a lot of clutter, and I doubt it results in much of a performance hit at all. It also removes any ambiguity about what is the proper label for a row in a MultiBalanceReport.

Calculate account leaf name at point of consumption.

---

hledger-web/static/hledger.css

I opened this PR to improve the font on different operating system. The new css chooses OS-specific font at first and fallback to Helvetic Neue, Helvetic, and Arial. I am new hledger new and this is my first contribution and I am not familiar with Haskell, so user interface at first.
Here is the difference, based on hledger-web demo on macOS:
Before
After
I Windows and Linux screenshots are needed, I will post later. Thanks.

Improve font display on different OS

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md
hledger/Hledger/Cli/CliOptions.hs
tests/csv.test

Hi @simonmichael, I've added a new config directive `separator`, with its behaviour outlined in my comment in #868. The command line flag `--separator` can be used to override the rules directive `separator`. If neither is specified, the separator defaults to `,`.
I have *not* yet added the documentation, (this is a draft PR) as I first wanted to check back with you on the semantics of the new feature. Please try it out and send me your comments, and I'll add the docs.

Add separator to config

---

hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
tests/timeclock.test

This should close #1169
Handle cases in timeclock format where a `i` line comes after an `i` line or an `o` line comes after an `o` line. See the shelltests which I added for details.

Bugfix in timeclock format parsing

---

hledger-web/Hledger/Web/Main.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger-web/hledger-web.cabal
hledger-web/hledger-web.m4.md
hledger-web/package.yaml

I wanted to run multiple instances of `hledger-web` behind an nginx reverse proxy, but wanted to get around an arbitrary `user -> port`-mapping.
Thus, my idea was to use unix socket files in a scheme like `/tmp/hledger-$username.socket`. This would allow to use an nginx directive like the following:
```
proxy_pass http://unix:/tmp/hledger-${remote_user}.socket;
```
Other usecases were also given in the IRC channel:
- `hpd_> maybe because unix sockets allow for proper access control`
- `alerque[m]> A socket would also be useful for local GUI wrappers.`
The main changes are:
- The code now requires Network.Socket (and thus `network` as a dependency)
- This gives us the functions to create a socket
- Introduces `--socket=/path/to/socket` option
- This implies `--serve`, as most browsers …

[WIP] web: Add option --socket to use UNIX socket file

---

hledger-lib/hledger_csv.m4.md
hledger-lib/hledger_journal.m4.md
hledger-lib/hledger_timeclock.m4.md
hledger-lib/hledger_timedot.m4.md
hledger/hledger_examples.m4.md
hledger/hledger_options.m4.md

Note that this PR does not change the bodies of these files to use yyyy-mm-dd formatting; some yyyy/mm/dd remain there, subject to discussion.

;doc: update shell output in hledger*/*.m4.md to use ISO date formatting

---

hledger-web/Hledger/Web/Main.hs
hledger-web/Hledger/Web/Settings.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger-web/hledger-web.cabal
hledger-web/package.yaml
stack.yaml

This PR closes #1145. It allows `hledger-web` to be reachable over IPv6, e.g. by calling it like
```
hledger-web --host ::1
```
- Modify the `--host` validation in `hledger-web/Hledger/Web/WebOptions.hs` to allow IPv6 addresses
- Modifies the default base URL to surround the host in `[` and `]` if an IPv6 address is used (required for proper IPv6-URLs in the browser)
- `Network.Wai.Handler.Launch.runHostPortUrl` uses the hardcoded host `127.0.0.1` to launch the browser. **Until there is a solution for https://github.com/yesodweb/wai-handlers/issues/1, this PR should probably not be merged, as the server is not reachable over the URL that is opened**
- This problem is not relevant if `--serve` is used.
- Not tested with [IPv4-mapped …

web: Add IPv6 support

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Read/Common.hs

Fix documentation, make ISO date format standard in some places

---

hledger-lib/Hledger/Data/Json.hs
hledger/hledger.m4.md

A proposed fix for #1195:
> Amounts in JSON are now rendered as simple Numbers with up to 10
decimal places, instead of Decimal objects which would in some cases
have 255 digits, too many for most JSON parsers to handle.
A provisional fix, see the comment in Json.hs for more detail.

json: use a simpler, more consumable number representation

---

hledger-lib/Text/Tabular/AsciiWide.hs

This fixes table edges always using single-width intersections and
adds support for double horizontal lines with single vertical lines
The last row in this table would previously not have used `╪` correctly on the ends or middle of the row.
```
┼───────────────────────────────╫────────┼────────╫──────┼
│                               ║  recvd │   paid ║ held │
╪═══════════════════════════════╬════════╪════════╬══════╪
```

cli:Improve pretty table rendering with double-wide characters

---

Makefile
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Utils/Debug.hs
hledger-lib/hledger_timedot.m4.md
tests/journal/parse-errors.test
tests/timeclock.test
tests/timedot.test

Following discussion in #hledger, here are two inter-related changes I'm considering merging, perhaps as soon as for tomorrow's 1.17 release. Though really, both of them probably need more testing than that. Here's the most disruptive one:
> For a long time hledger has auto-detected the file format when it's
not known, eg when reading from a file with unusual extension (like
.dat or .txt), or from standard input (-f-), or when using the include
directive (which currently ignores file extensions).
> 
> Auto-detecting has been done by trying all readers until one succeeds.
This could guess wrong in some cases, but it was so rare that it has
been working fine.
> 
> Recently, more conveniences have been added to timedot format,
increasing its overlap with journal format, which makes this kind …

more org support in timedot; drop format auto-detection

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.5
hledger-lib/hledger_csv.info
hledger-lib/hledger_csv.m4.md
hledger-lib/hledger_csv.txt
tests/csv.test

A rewrite and simplification of the posting-generating code. The
"special handling for pre 1.17 rules" should now be less noticeable.
amount1/amount2 no longer force a second posting or explicit amounts
on both postings. (Only amount/amount-in/amount-out do that.)
Error messages and handling of corner cases may be more robust, also.
@adept, does it sound ok ? This scheme seems like one we would have considered, but I think maybe we didn't, perhaps because the old code really didn't allow it.

simpler, more flexible generation of postings from csv

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md

The ordering of journalfieldnames is changed in order to comply with the requirement stated in the comment:
"Names must precede any other name they contain, for the parser".
If left unchanged, "account1" would precede "account11", "account12", and so on, which would break the parsing.
With the new ordering, "account11" precedes "account1".

csv: Increase maximum number of postings in CSV reader from 9 to 99.

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/Hledger/Cli/Commands/Balance.hs

All call sites of multiBalanceReport do `multiBalanceReport opts (queryFromOpts d opts)`.
I think it is best to move derivation of query inside `multiBalanceReport` to reduce the "gotcha" factor, as passing a query that is "wider" than period requested in opts (like `Any`) effectively renders period selection in opts null and void -- I discovered that a painful way while playing with multiBalanceReport in ghci

lib: multiBalanceReport derives query from ReportOpts

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/hledger_journal.m4.md
hledger/hledger.m4.md
tests/journal/valuation.test
tests/journal/valuation2.test

WIP for #1239, untested and may not work yet. Draft docs:
```hs
-- When the valuation commodity is specified, this looks for an
-- exchange rate (market price) calculated in any of the following
-- ways, in order of preference:
--
-- 1. a declared market price (DMP) - a P directive giving the
--    exchange rate from source commodity to valuation commodity
--
-- 2. a transaction-implied market price (TMP) - a market price
--    equivalent to the transaction price used in the latest
--    transaction from source commodity to valuation commodity
--    (on or before the valuation date)
--
-- 3. a reverse declared market price (RDMP) - calculated by inverting
--    a DMP
--
-- 4. a reverse transaction-implied market price (RTMP) - calculated
--    by inverting a TMP
--
-- 5. an indirect …
```

lib: also infer market prices from transactions, like Ledger

---

hledger-lib/Hledger/Query.hs
hledger-web/Hledger/Web/Foundation.hs
hledger-web/Hledger/Web/Handler/JournalR.hs
hledger-web/Hledger/Web/Handler/RegisterR.hs
hledger-web/Hledger/Web/Widget/Common.hs
hledger-web/templates/balance-report.hamlet
hledger-web/templates/register.hamlet

This is an experimental feature
that I proposed already last year in googlegroups.
I am annoyed that date restrictions get lost
when I traverse through the accounts on the left sidebar.
Thus I added the non-inacct parts of part to the account links.
I could also add these to the links in the journal and the register.
It works only if the query was already sent to the server.
I hope I got the quotation right.
I had to export Query.prefixes.
Alternatively I could move replaceInacct to the Query module.

;web: maintain query when choosing a different 'inacct' account on the sidebar

---

hledger-lib/Hledger/Data/Amount.hs
tests/journal/parse-errors.test

The issue is that `isNegativeMixedAmount` does not return `Just False` for _positive_ mixed amount, so new sign-checking code ignores any such mixed amount completely and falsely thinks that all remaining amounts are of the same sign.

lib: test for issue with sign checking code + fix

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/hledger_journal.m4.md
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Utils.hs
tests/forecast.test

Given that we already have a nice single place where "forecast begin" and "forecast end" is defined, plugging in options that allow overriding one or both of the values is pretty straightforward. I added a test nevertheless

lib: --forecast=PERIODICEXPR. Fixes #835, #1236

---

hledger-ui/Hledger/UI/UIState.hs

Does what it says on the tin.
Tested with this journal:
```
~ monthly from 2020-05-01   forecast
a   1
b
2020-06-10 Past
a    10
b
2020-10-06 Future 
a    1000
b
```
Pressing `F` causes the future transaction to appear

ui: fix regression in 'F' (fixes #1255)

---

hledger/Hledger/Cli/Commands/Print.hs

Couple of changes to csv output of "hledger print":
1. digit group separators suppressed in amounts
2. prices suppressed in amounts
3. added posting idx
Result of (1) + (2) is that amount are now properly numeric (and thus CSV output could be used in number-munching applications like python or R)
Effect of (3) is nice to have if your transactions are always built is predictable way, as it allows you to choose/filter for first/second/last posting, etc

cli: changes to "hledger print -O csv" output

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md
tests/csv.test
tests/csvtest.sh

This closes #1252  and fixes seemingly long-standing issue in csv rules parser where excessive backtracking prevented proper error reporting. 
I've also found out that `blocksAssigning` occupy 50-60% of the run time, and memorized it. This yields ~50% speedup on my files.
I've added tests to illustrate error messages + a bunch of test cases for #1252  + docs

lib: condition tables in csv rules + tests

---

hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Print.md
hledger/hledger.m4.md

This adds support for `-O sql` to `hledger print` + some minimal docs.
`hledger print -O sql` will output commands to create `postings` table with structure mimicking the CSV output:
```
$ cat /tmp/1.journal
2020-06-10 Past
a    10
b
2020-10-06 Future 
a    1000
b
$ hledger print -O sql -f /tmp/1.journal
create table if not exists postings(postidx serial,txnidx int,date1 date,date2 date,status text,code text,description text,comment text,account text,amount numeric,commodity text,credit numeric,debit numeric,posting_status text,posting_comment text);
insert into postings(txnidx,date1,date2,status,code,description,comment,account,amount,commodity,credit,debit,posting_status,posting_comment) values
('1','2020-06-10',NULL,NULL,NULL,'Past',NULL,'a','10',NULL,NULL,'10',NULL,NULL) …
```

cli: print -O sql

---

hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
tests/balance/373-layout.test
tests/balance/sorting.test

This PR aims to accomplish two major goals:
-  Get boring parent ellision working for `multiBalanceReport`
-  Remove the special `BalanceReport` code, and just use `multiBalanceReport`
I believe it does both, with the following additional benefits:
- A refactor of `multiBalanceReportWith`, to make the structure easier to follow, and with a clearer division of responsibilities
- All decisions for how an account name is to be displayed are now made in `multiBalanceReport`, rather than scattered around the code base
- Some miscellaneous improvements in account name rendering, including `--drop` now working with `MultiBalanceReport`s, and addressing some of #373

Use multiBalanceReport for balanceReport

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
tests/balance/drop.test

When using --drop with --tree and boring parent ellision, previously all parents were mistakenly considered boring. Fix this, and add some tests so this doesn't happen again.

lib: Fix interaction of --drop, --tree, and boring parent ellision.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-web/Hledger/Web/Widget/Common.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
tests/balance/multicommodity.test

Multicolumn balance reports showing many commodities tend to become
unreadably wide, especially in tree mode. Now by default we show at
most two commodities, and a count of the rest if there are more than
two. This should help keep reports somewhat readable by default.

balcmds: elide amounts with 3 or more commodities, unless --no-elide

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md
tests/csv.test

This adds support for the `&` operator in conditional blocks for CSV rule files. A more general alternative would be nested if statements, but that seems to be a bit more involved from what I can tell.
No prior Haskell experience, so any feedback is much appreciated.

csv: Add support for & operators in conditional blocks

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Utils/String.hs
hledger-lib/Hledger/Utils/Text.hs

Remove some instances of `reverse . take n . reverse`, and use some text library functions.
Note that the text library stripping functions have slightly different behaviour, as they will remove all whitespace characters instead of just spaces and tabs, but none of the tests seem to fail.

Use some text library functions, avoid reversing twice.

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/Hledger/Cli/Commands/Accounts.hs

This just makes the treatment of depth as an option more uniform, and cleans up some of the function calls.

lib: account name clipping takes Maybe Int as depth.

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger-lib/Hledger/Utils/String.hs
hledger/Hledger/Cli/Commands/Add.hs

This replaces all uses of `skipMany spacenonewline` with `takeWhileP isNonNewlineSpace`, and similarly for `skipSome` and `takeWhile1P`.
Profiling suggested this would give some performance improvements. Evidence for actually getting this improvement is mixed:
- quickbench is showing no significant difference in run time.
- running `hledger balance assets +RTS -P` on my system suggests a roughly 8% decrease in total time and total memeory allocation.
In any case, I think this change probably gives improvements, and is unlikely to cause any harm.

lib: Speed up space parsing

---

hledger-lib/Hledger/Data/Commodity.hs
tests/journal/amounts-and-commodities.test

Does what it says on the tin :)
We already disallow `\n` and space, so adding `\t` there seems logical. I threw in a test for a good measure

lib: disallow tabs in simplecommoditysymbolp (fixes #1301)

---

hledger-lib/Hledger/Data/Dates.hs

Unfortunately I was not able to run the tests.
Nevertheless, I added some doctest examples.

implement parsing of "q1" and "2020q1"

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Types.hs

This changes the representation of SmartDate to make ill-formed SmartDates unrepresentable. The represtation has an extra two cases, but makes the different behaviour of SmartDates more clear. This makes `spanFromSmartDate` total, and simplifies a few of the parsers.

lib: Make ill-formed SmartDates unrepresentable.

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs
tests/incomestatement.test

Partly addresses #1309. I'm not sure what the original rationale for this was, but it seems like something the user should be able to control themselves. The fact that the behaviour of `--no-total` in compound balance reports has changed recently may also be justification for removing this.

cli: No longer force --no-total in compound balance reports when using --percent.

---

stack.yaml

This PR enables `-split-sections` for the stack build of `hledger` and its dependencies. This reduces the size of the `hledger` binary on my machine from 27mb to 13mb.
How are the official releases made? Should this setting be activated elsewhere?

`-split-sections` everywhere

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-ui/Hledger/UI/UIUtils.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Utils.hs

Also gets rid of the partial functions `parsedate` and `mkdatespan`, used entirely with hard-coded arguments (with one exception). Use the total functions `fromGregorian` or `parsedateM` instead.

lib,cli,ui: Remove old CPP directives made redundant by version bounds.

---

bin/hledger-smooth.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Period.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Utils/Text.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Prices.hs

Partly addressing #1325, a lot of uses of `fromIntegral` come from the fact that `Decimal` uses a `Word8` to store the precision, while `Amount` uses an `Int`. If we use `Word8` for `aprecision`, we save 7 uses of `fromIntegral`.
Issues this raises:
- There are two magic precision values `maxprecision` and `maxprecisionwithpoint`. With a domain of `Word8` rather than `Int`, this is a much larger target for accidentally hitting.
- People might try to input large (i.e. >255) precision values and get wraparound effects. This was also true before, before it only happened when you actually called `roundTo`. Now it appears a bit earlier.
Another 19 instances are eliminated by replacing `fromIntegral . length` with `genericLength`, replacing `fromIntegral` with `toInteger` when appropriate, or …

Replace some uses of fromIntegral with safer calls

---

shell-completion/hledger-completion.bash

I updated the shell completions for new options and new commands in version 1.19.
I also contacted the Arch packager if he can add the completion in the installation script.

Update shell completion for current master

---

hledger-web/Hledger/Web/Foundation.hs
hledger-web/hledger-web.cabal
hledger-web/package.yaml

https://github.com/simonmichael/hledger/pull/1228
#1081 
It would be more correct to put the file in XDG_RUNTIME_DIR, but it is not supported by `directory`. But XDG_DATA_DIR seems OK, too. `directory` handles platforms other than Linux.

web: Put session file in $XDG_DATA_DIR.

---

hledger-lib/Hledger/Utils/String.hs
tests/i18n/unicode-account-matching.test

Addresses #1364.
The commit which broke this was 7d1e6d7d12f3c3a042661c1d6963523b5d5f676b, which changed `quoteIfNeeded` so that it actually quotes things (albeit apparently incorrectly). It previously spent several years as the identity function with nobody noticing. This raises the question: is this function actually needed at all?
Edit: Correction to the above. quoteIfNeeded was not the identity function, but it did spend several years not escaping quotes. Should it attempt to do so? Can we find an example of something which doesn't work if it doesn't escape quotes?

lib: quoteIfNeeded should not escape the backslashes in unicode points

---

hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Tags.hs
tests/cli/query-args.test

This is proof of concept for addessing #1368 by sidestepping quoting altogether. Queries are no longer wrapped in quotes and escaped, because they are stored term-by-term in a list, so no quoting is necessary.
I do not propose adopting this as is (at the very least there are conflicts with #1340), but to solicit feedback on the approach. The important changes are in `Query.hs` and `ReportOptions.hs`.

Use [Text] for querystring_ instead of Text, to get around quoting problems.

---

hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Reports/ReportOptions.hs

The Empty query constructor has done nothing for at least 9 years. I think this is a reasonable candidate for removal.
The only question is whether we should continue to accept the `empty:` prefix when parsing query terms. I've removed it here, but if you think it should continue to parse successfully (presumably as `Any`), let me know. I somewhat doubt anybody uses this ever.

lib: Remove Empty Query constructor, which does nothing and has done so for a very long time.

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/UIState.hs

Addresses some regressions. Changing the depth in hledger-ui now actually filters the postings, rather than just update the counter.
[Fix for #1340]

lib,ui: Make sure ReportSpec is updated when updating ReportOpts.

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/balance/depth.test
hledger/test/balance/intervals.test
hledger/test/balance/percent.test
hledger/test/forecast.test
hledger/test/journal/valuation.test

This was previously done for CompoundBalanceReport and when --empty was
called; this makes the behaviour consistent.
Addresses #1396, and should also address part of #1405 (see test #30 in valuation.test).

lib: Include empty columns in a MultiBalanceReports.

---

hledger/Hledger/Cli/Commands/Accounts.md
hledger/Hledger/Cli/Commands/Accounts.txt
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Balance.txt
hledger/Hledger/Cli/Commands/Print.md
hledger/Hledger/Cli/Commands/Print.txt
hledger/Hledger/Cli/Commands/Register.md
hledger/Hledger/Cli/Commands/Register.txt

These one-letter a, b, p, r command aliases for accounts, balance, print, register are less good than the more common three-letter ones: less mnemonic, less clear when reading, and impractical with shell completions. (And "txns" for print will never catch on I think.) So in master I deprecated these aliases, hiding them from the commands list, though they still work. 
Too many alternatives creates confusion, and I'd like to remove them entirely, but I have seen a few people using them.  I have posted this PR for discussion, and will cc the mail list. Any thoughts ?
A related change that might help with backward compabitility, at the cost of less careful command selection: always run the first command whose name matches the command argument, rather than requiring an unambiguous prefix. [ …

[RFC] cli: drop deprecated command aliases a, b, p, r, txns

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/push.yml
.github/workflows/windows.yml
Makefile
bin/compile.sh
bin/hledger-balance-as-budget.hs
bin/hledger-check-fancyassertions.hs
bin/hledger-combine-balances.hs
bin/hledger-smooth.hs
bin/hledger-swap-dates.hs
bin/scripts.test
hledger-lib/Hledger/Reports/BudgetReport.hs

The [add-on scripts in bin/](https://hledger.org/scripting.html#haskell-scripts) always fall behind hledger-lib/hledger API changes because we don't test them. We describe them as just examples and possibly broken, but that is unsatisfying and leads to intermittent manual catchup work. I think we need to include them in tests so as to keep them building, at least. This PR adds a test for that. If this is a good idea, next we need to update the scripts to make the tests pass.

ci: also test compilation of bin/ add-on scripts

---

hledger-lib/Hledger/Read/Common.hs

AUTO commodity is a placeholder for postings with missing amounts. It
should be ignored when doing a strict commodity check.
Fixes #1419

journal: Ignore AUTO commodity when strict checking

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/journal/valuation.test

Addresses #1428. @aragaer, could you let me know if this gives you the results you expect?
Also adds a postingDate argument to amountApplyValuation, and re-orders the ValuationType and (Transaction/Posting) arguments to (transaction/posting)ApplyValuation, to be consistent with amountApplyValuation.
Also addresses #1424.
The test failures are present in master. I've put a fix in commit a023fc880b00b85be3cde19f16af014c81edfde5 in PR #1427. I'll rebase this once that is merged or cherry-picked.

lib,cli: Extend --value=then valuation to all report types.

---

hledger/hledger.m4.md

Across the rest of the documentation and other accounting documentation
it appears to imply that the more traditional top level name would be
revenue. In fact the income statement says that is a subtraction between
revenue and expenses to derive the income. While the account types that
hledger supports are named revenue so it seems more natural to name this
revenue.

;doc: adjust traditional top level accounts

---

hledger/Hledger/Cli/Commands/Roi.hs
hledger/test/roi.test

This fixes #1446 by providing a better error message. 
I can write a better code that makes sure that all amounts could be valued (based on inferred prices) via `mixedAmountValueOnDate`  later, but I will not be able to do it in time for 1.20.3. 
I am not sure that I need to use `mixedAmountValueOnDate` explicitly -- i would prefer for journal reading code to do this for me, but it does not seem to work. I was sure that simply adding `--value ... --infer-value` to roi invocation will infer missing prices for me, but it does not seem to be the case.
Example journal:
```
2019/11/01 Example
Assets:Checking  -1 A
Investment       10 B
2019/11/02 Example
Investment        -10 B @@ 1 A
Assets:Checking    12 A
Unrealized PnL
```
Command: `hledger -f example.journal roi -p 2019-11 --inv …

lib: better message when roi fails to value commodity, fixes #1446

---

examples/roi-unrealised.ledger
hledger/Hledger/Cli/Commands/Roi.hs
hledger/test/roi.test

with this change, roi supports full variety of --value switches AND takes into account value changes due to price directives.
Instead of valuing all transactions upfront and working with the result, roi now applies valuations if/when needed, with proper date/periodend values, and additionally visits all dates on which we have price directives to make sure it "samples" value of the investment on that date.
This renders unnecessary "fake sell-rebuy" transactions that were shown in examples/roi-unrealised.journal (and mentioned as part of the workaround script in #1473) and closes #1267

roi: use Valuations throughout the code

---

examples/roi-unrealised.ledger

I've decided to comment roi-unrealised.ledger and leave a reference to Cookbook there, as the approach taken by the author of this example is somewhat unorthodox and not something that I would personally recommend copying.

doc: explain roi-unrealised.ledger, reference to cookbook

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/journal/valuation.test
hledger/test/journal/valuechange.test

Addresses some of the discussions of #1353.
I've done my best to make sure this matches up with the agreed-upon interface, and that the tests are correct and comprehensive, but given how much change there's been here in the last few months it's very possible I've made a mistake somewhere. Extra eyes would be appreciated.

Implement new --valuechange interface, restore old --value=end behaviour.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/test/balance/budget.test
hledger/test/journal/valuation.test

Addresses points raised in #1416. If it is decided that price directives should also be included for any valuation, rather than just period end, let me know and that can be adjusted.
Also gets rid of some code duplication for calculating report spans.
As a side effect, this enlarges the reportspan to encompass full intervals for budget goals. This was documented in the tests, but it's not clear whether that was desired behaviour or just documenting quirks. If we want budget goals to have a different range than the actual report, let me know and I can reinstate the old behaviour.

Do not include price directives in report span unless valuing at period ends.

---

bin/_hledger-chart.hs
bin/hledger-check-fancyassertions.hs
bin/hledger-combine-balances.hs
hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/TransactionModifier.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger-lib/Hledger/Reports/TransactionsReport.hs
hledger-lib/Hledger/Utils.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Balancesheet.hs
hledger/Hledger/Cli/Commands/Balancesheetequity.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Registermatch.hs
hledger/Hledger/Cli/Commands/Roi.hs

This is a collection of refactorings, cleanups, and performance improvements. I think that all of this should be relatively uncontroversial, though there are a couple of follow-ups this suggests which may be controversial (I have therefore broken them off into a separate PR which will follow this).
Points to consider:
- The `Num` instance for `MixedAmount` is no longer used anywhere in this codebase. We could just remove it (morally the right thing to do), but this would have a big effect on the API.
- I have gone through and replaced every usage of `sum` for `MixedAmount` with `mconcat` (or `foldMap` applied to an appropriate function), and every usage of `sumStrict` with `foldMap'` applied to an appropriate function. Since all these locations are now marked, we may want to consider if …

MixedAmount and other cleanups

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Register.hs

These are the commits from #1491 concerning the `showMixedAmountB` function, and splitting it into `showMixedAmountB` and `showAmountsB`.
It continues to be the case that most users should continue using the simple `MixedAmount -> String` variants, and for those who want more control, `showMixedAmountB` is almost always what you want. `showAmountsB` is for when you have a list of amounts which you do not want normalised before being shown, as in when you're showing a transaction or posting (in which case, you should probably be using `postingsAsLines`, which calls this internally). `showAmountsLinesB` is a minor variant which gives you a builder for each line (since we're using builders for efficiency, we cannot call T.lines without strictifying).

Allow showing lists of Amounts, make showing register reports and lists of postings more efficient.

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Text/Megaparsec/Custom.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-web/Hledger/Web/Widget/AddForm.hs
hledger-web/templates/add-form.hamlet
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Check/Uniqueleafnames.hs
hledger/Hledger/Cli/Commands/Commodities.hs
hledger/Hledger/Cli/Commands/Payees.hs

I've broken off some of the simpler commits originally in #1491. All these commits are minor refactors, documentation fixups, and efficiency improvements which are mostly minor, but become significant with larger journals.
The only API changes are the addition of a few Set-based functions getting various journal parameters, a list of which is in e120861.

Performance cleanups

---

hledger-lib/Hledger/Data/Json.hs
hledger/test/json.test

It now uses the same JSON representation as Maybe Word8. This means that the JSON serialisation is now broadly compatible with that used before the commit f6fa76bba7530af3be825445a1097ae42498b1cd, differing only in how it handles numbers outside Word8 and that it can now produce null for NaturalPrecision.
Addresses #1360.

lib,test: Simplify the JSON representation of AmountPrecision.

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/test/csv.test

This allows the sign simplification to ignore leading and trailing spaces. This is especially important for leading spaces where a leading space causes the eventual amountp parser to fail.
Example problem input now allowed: `"+ $1"`

Tolerate spaces in amount fields in CSV files

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/test/balance/transpose.test

It was reported on #hledger that bal -O csv capitalises "account"
differently for single and multi-period reports. All lower case seems
to be the most common, so I have dropped the capitalisation. Also
the trailing colon from --transpose's "total:".

bal: keep csv column and row labels consistently lower case

---

hledger-lib/Hledger/Data/Ledger.hs
hledger/Hledger/Cli/Commands/Stats.hs

Fixes #772.
There may be a conversation to be had here on the value of `Hledger.Data.Ledger`. Aside from `ledgerFromJournal`, these functions are only used in two places in our codebase. As seen here, this kind of little-used functionality can lead to bugs. We could just trim out all functions aside from `ledgerFromJournal`, but this will affect the API.

lib,cli: Fix ledgerDateSpan, so that in takes transaction dates into account.

---

hledger-lib/Hledger/Data/Json.hs
hledger/test/json.test

Removes an unnecessary increase in precision for JSON representations for some Quantity.
Adds more efficient `toEncoding` definitions for some custom `ToJSON` declarations.

Tweak JSON serialisation

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils/Debug.hs

- lib: useColor, colorOption helpers usable anywhere
- lib: debug output now respects --color/NO_COLOR/ANSI support
- lib: debug output checks for color support on stderr, not stdout
I was capturing debug output into files for comparison, and couldn't turn off the ANSI codes. Debug output is part of "output" and users expect to control color there too. 
This adds a few more functions using unsafePerformIO to read IO state, similar to `debugLevel` but a little more adventurous - these ones check existence of an environment variable, and I suppose not necessarily at program startup. I think this usage is safe enough though. Also, I blindly copied the no-cse and NOINLINE pragmas, hopefully in a useful way.
Related: https://hledger.org/hledger.html#general-options -> `--color`

control color in debug output

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/UITypes.hs

Also leave at least 15 spaces for account names.
This addresses #1474 , and goes some way to addressing #1478.

ui: In account screen, elide amounts which go past the specified width.

---

hledger-web/static/hledger.js

This fixes an issue in `hledger-web` related to the final amount input in the AddForm not getting initialized correctly. I discussed this issue with @simonmichael in the #hledger IRC channel.
The AddForm is the form that is used to add a transaction, and includes inputs for the date, description, and four account/amount input field pairs. Typing in the final amount input should add additional rows for more accounts/amounts, but is not working correctly as of `hledger-web-1.21`.
Currently the AddForm can be accessed in one of three ways:
1. Via keypress, by pressing `e` or `a` on your keyboard
2. Via the "Add a transaction" `<a>` tag on the `/journal` page
3. Via the `/add` page
Prior to the change in this PR, only (1) above would correctly initialize the event listeners in the AddForm. To …

web: Fix keypress listener in final input of AddForm not getting initialized correctly

---

hledger/hledger.m4.md

Somebody in the Google group expressed surprise that their quarterly report ended at the end of the quarter, even though they specified an explicit end date in the middle of the of the quarter. It seems that the manual on report intervals does not mention this fact: it is left to later in the period expressions section. I've added a note about this.

Mention expansion of report start and end dates in report intevals documentation.

---

hledger-lib/Hledger/Data/Transaction.hs
hledger/test/journal/auto-postings.test
hledger/test/journal/parse-errors.test

There is a bug in `priceInferrerFor` which causes it to infer prices with the wrong sign whenever the two amounts its inferring for have the same sign. The resulting transaction would then fail to balance, so the error would be caught by a later check.
This changes it so that `priceInferrerFor` would infer the correct price in these cases, but adds a check so that it will not attempt to infer prices whenever the two amounts have the same sign.

lib: Do not attempt to infer price when amounts have the same sign.

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Utils/String.hs
hledger-lib/Hledger/Utils/Text.hs
hledger-lib/Text/Tabular/AsciiWide.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UITypes.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Commands/Stats.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

This cuts a few unnecessary conversions out, and allows us to remove/clean up a large amount of redundant utility code.

Clean up some String/Text utility code.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-web/Hledger/Web/Widget/AddForm.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Check.hs
hledger/Hledger/Cli/Commands/Check.md
hledger/Hledger/Cli/Commands/Diff.hs
hledger/Hledger/Cli/Commands/Import.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/check-balancednoautoconversion.test
hledger/test/journal/transaction-prices.test

This can be used on its own with the --no-infer-prices option, but is also enabled by --strict.
This at least partially addresses #86, #115, and #1177.

Add option to disable automatic price inferral in unbalanced multicommodity transactions.

---

bin/hledger-swap-dates.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Reports/TransactionsReport.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-web/Hledger/Web/Handler/JournalR.hs
hledger/Hledger/Cli/Commands/Check/Ordereddates.hs
hledger/Hledger/Cli/Commands/Checkdates.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Commands/Tags.hs

Doing costing and valuation for amounts is a bit confusing; every report handles it differently. This was fine when valuation was simpler, but now that we have `--value=then`, `--value=end`, `--valuechange`, and soon `--gain`, this means a lot of duplicated code handling special cases.
This PR simplifies things by defining one master valuation function which should be used in most cases: `journalApplyValuationFromOpts`. It does the following based on the `ReportSpec`:
- Convert to cost
- Strip prices if able
- Apply valuation
The only place this function is not sufficient is when performing `--value=end` valuation on balance reports that require you to sum amounts, such as the historical balance report. To handle these cases, we introduce `mixedAmountApplyValuationFromOptsWith`, which …

Clean up valuation functions, and make clear which to use where.

---

hledger-lib/Hledger/Utils/Debug.hs
hledger-ui/Hledger/UI/UIState.hs

[Another instance of #1556.]
A couple of issues raised from this.
1. `plog` is no longer used anywhere in the code base. It's not clear to me what purpose it is supposed to server over `dbg`, and every instance of its use in the code caused some sort of bug. Should we just remove it?
2. `clearCostValue` is only used in one place: when reloading the journal file in the transaction screen. Why that code is implemented the way it is is very confusing to me (and I'm not the only one judging by the code comments), but there are some strange things in there likely to be bugs. In particular, `regenerateTransactions` uses the old `rspec`, not the new one that results from `clearCostValue`. If anybody knows more about what should happen here and what I should be looking for, it would help with …

Don't write debug.log when reloading the journal in hledger-ui's transaction screen

---

hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIState.hs

This fixes a bug where, when reloading journal files by pressing `g` or using the `--watch` command, the `cost_` and `value_` flags would not be reset without pressing `g` a second time.

In hledger-ui TransactionScreen, set the current transaction based on RegisterScreen.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Types.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/test/balance/sorting.test

Addresses #1563. <s>When comparing MixedAmounts, only the list of Quantities is considered</s>. Now substitutes an amount of quantity 0 for any missing commodities when doing comparisons.

more useful sort order for multi-commodity MixedAmounts: treat missing commodities as 0

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-web/Hledger/Web/Handler/RegisterR.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balancesheet.hs
hledger/Hledger/Cli/Commands/Balancesheetequity.hs
hledger/Hledger/Cli/Commands/Cashflow.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Some renaming that seemed helpful as I contemplated working on something (named budgets). Types now match the terminology at https://hledger.org/hledger.html#balance-report-types, constructors are shorter, and there's no longer a constructor with the same name as the unrelated `BudgetReport` type. Any feedback welcome.

ref: bal: rename some report types to clarify/sync with docs

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/TransactionModifier.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/test/journal/parse-errors.test
hledger/test/json.test

In Amount, aismultiplier is a boolean flag that will always be False,
except for in TMPostingRules, where it indicates whether the posting
rule is a multiplier. It is therefore unnecessary in the vast majority
of cases. This PR pulls this flag out of Amount and puts it into
TMPostingRule, so it is only kept around when necessary.
This changes the parsing of journals somewhat. Previously you could
include an `*` before an amount anywhere in a Journal, and it would
happily parse and set the aismultiplier flag true. This will now fail
with a parse error: `*` is now only acceptable before an amount within an
auto posting rule.
This changes the JSON output of Amount, as it will no longer include
aismultiplier.

lib: Remove aismultiplier from Amount.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/TransactionModifier.hs
hledger-lib/Hledger/Read/Common.hs
hledger-web/Hledger/Web/Test.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/journal/auto-postings.test

Addresses #1412.
The second commit here is a minimal fix for the problem. The first was work I did while trying to understand where the problem is.
<s>I actually think that generating the forecast transactions should happen in journal finalisation, not as a separate step after the journal has already been finalised.</s> This would avoid having to re-balance the whole journal several times.

Add balancing amounts in periodic transactions before applying auto postings

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger/test/aregister.test
hledger/test/journal/amounts-and-commodities.test

<s>Explicitly avoid filtering by depth queries, perform valuation after all reportq filtering is done (in both the historical and recent postings), and make sure filtering is done at the correct point based on whether --txn-dates is set.</s> (#1634)
Make sure the reportq properly excludes depth, currency, and amount queries. Do not transform transactions (except as documented) unless we keep the original transaction.

Make sure aregister correctly identifies historical postings (#1634)

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger/test/aregister.test

then by parse order to break any ties. (#1642)

fix: areg: Make sure aregister sorts first by transaction register date,

---

hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-web/Hledger/Web/Test.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/forecast.test

Add forecast transactions at journal finalisation, rather than as a post-processing step.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/StringFormat.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils/Text.hs
hledger-lib/Text/Tabular/AsciiWide.hs
hledger-lib/Text/WideString.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/balance/commodity-account.test

This is a potential implementation of proposals (6) and (10) from https://github.com/simonmichael/hledger/issues/1559. These commits handle the `balance` family of commands but should be extendable to `compound-balance` family as well.

bal: Show commodity symbol as a subaccount / in a column

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Text/Tabular/AsciiWide.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/balance/commodity-column.test

I was introducing `--commodity-column` into my personal reports and realized that the textual output didn't correctly handle `--transpose`  when both flags are set. While fixing that, I also realized that empty commodities were being silently filtered out (e.g https://github.com/simonmichael/hledger/blob/master/hledger/Hledger/Cli/Commands/Balance.hs#L717). This wasn't a regression per-se but obviously undesirable behavior.
There is some overlap with https://github.com/simonmichael/hledger/pull/1649 since handling transposition unfortunately involved some reworking of the compound call-site.
Perhaps the suite of flag interactions should be more formally considered?

fix: bal: fix commodity-column interaction with transpose and empty commodities

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Utils.hs
hledger/hledger.cabal
hledger/package.yaml

This eliminates old-time, which has been deprecated for a while, from
our dependencies.
This introduces a slight incompatibility, as a small number of functions
now take/return POSIXTime instead of ClockTime. Generally you will be
using the current time, in which case you should use getPOSIXTime from
Data.Time.Clock.POSIX instead of getClockTime.
utcTimeToClockTime has been removed, as it is now equivalent to
utcTimeToPOSIXSeconds from Data.Time.Clock.POSIX.

pkg!: Migrate the last of old-time over to time, changing ClockTime to POSIXTime.

---

hledger/hledger.1
hledger/hledger.info
hledger/hledger.m4.md
hledger/hledger.txt

Just a quick typo fix,
```
hledger: command f- is not recognized, run with no command to see a list
```
is obviously not what the example is supposed to print :)

Fix cmdline example typo, f- should be -f-

---

hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Period.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/test/cli/report-interval.test
hledger/test/journal/valuation.test
hledger/test/pivot.test
hledger/test/register/depth.test
hledger/test/register/intervals.test

Fixes #1655.
As a side effect, this changes the Json representation of the PostingsReport. The maybe report end date is now replaced with a maybe period.
I think this will provide strictly more information, and so is a desirable change, but if it will break too much we can change it back.

fix!: register: Tighten up spacing around the date in register reports. (#1655)

---

hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/test/aregister.test

Fixes #1656.
This also switches to the renderTable interface for laying out aregister, just as in postingsReport.

fix: aregister: Make multicommodity amounts are properly aligned in aregister.

---

hledger-web/Hledger/Web/Widget/AddForm.hs
hledger-web/hledger-web.cabal
hledger-web/package.yaml
stack8.6.yaml
stack8.8.yaml

This fixes a reported Stored XSS vulnerability in toBloodhoundJson by
encoding the user-controlled values in this payload into base64 and
parsing them with atob.
In my exploration of the vulnerability with various payloads I and
others crafted, it would appear that this is the only available XSS in
hledger-web in relation to stored accounts and transaction details. If
there is other parts of the UI which may contain user-controlled data,
they should be examined for similar things. In this instance,
protections provided by yesod and other libraries worked fine, but in a
bit of code that hledger-web was generating, the user could insert a
</Script> tag (which is valid HTML and equivalent to </script> but not
caught by the T.Replace that existed in toBloodhoundJson) in order to
switch out of …

web: base64 encode user controlled strings (#1525)

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/balance/no-total-no-elide.test

Previously we only showed empty leaves.
Fixes #1688.

fix: balance: Show all empty accounts in flat balance reports. (#1688)

---

hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-web/Hledger/Web/Foundation.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Commands/Stats.hs
hledger/Hledger/Cli/Commands/Tags.hs
hledger/hledger.m4.md

Fixes #1674.
This is so that we can run tests containing future transactions that
won't fail as soon as ‘the future’ actually arrives.

test: cli: Add --today option to explicitly set the current date. (#1674)

---

hledger-web/Hledger/Web/Foundation.hs

--empty. (#1237)
Calling with --empty now overrides any cookies determining whether
zero accounts are hidden.

fix: web: Toggle showing zero elements properly even when called with

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/hledger.m4.md

This change gives the ability to write `comment \nIBAN: %iban\nBIC:%bic` or `comment1 \nIBAN: %iban\nBIC:%bic` and have every tag on a new line.

lib: Allow multiline comments in csv rules

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs

mixedAmount(Looks|Is)Zero now operate directly on the MixedAmount,
rather than converting them to a list of amounts first.
mixedAmountCost no longer reconstructs the entire MixedAmount when there
are amounts with no cost.
transactionCheckBalanced only checks if signs are okay if sums are not
okay. It also only traverses the list of postings once when picking real
and balanced virtual postings.
accountNamesFromPostings now uses a Set instead of nubSort.

ref: performance: Improve performance for some high-use functions.

---

hledger-lib/Hledger/Data.hs
hledger-lib/Hledger/Data/Balancing.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml

The general thrust of these changes is to try to flatten the module structure to improve compile times, and enable future changes for which the current module structure is causing import cycles. This generally follows the advice [here].(https://www.parsonsmatt.org/2019/11/27/keeping_compilation_fast.html)
A summary of the main changes:
- Functions related to balancing `Transaction` and `Journal`s have been moved out into a separate module `Hledger.Data.Balancing`. This shrinks the massive `Journal.hs` module, and groups related balancing functions together.
- The `Hledger.Read` and `Hledger.Reports` are now almost entirely independent. Since `Hledger.Read` is one of the big bottlenecks for complilation times, this should enable work on getting this down.
This PR is largely setting the …

Some changes to the module structure

---

hledger-lib/Hledger/Data/Balancing.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-web/Hledger/Web/Widget/Common.hs
hledger/Hledger/Cli/Commands/Check/Ordereddates.hs
hledger/Hledger/Cli/Commands/Check/Uniqueleafnames.hs
hledger/Hledger/Cli/Commands/Rewrite.hs

or (SourcePos, SourcePos).
This has been marked for possible removal for a while. We are keeping
strictly more information. Possible edge cases arise with Timeclock and
CsvReader, but I think these are covered.
The particular motivation for getting rid of this is that
GenericSourcePos is creating some awkward import considerations for
little gain. Removing this enables some flattening of the module
dependency tree.

lib!: Remove GenericSourcePos, and replace it with SourcePos

---

.gitignore
doc/common.m4
hledger-lib/Hledger/Data/Amount.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/hledger.m4.md
hledger/test/cli/commodity-style.test

This PR:
- Changes the behavior of applying commodity styles (such as those set by the  the -c/--commodity-style option) to include applying it to amount prices (except for precision, which is not affected). 
- Changes -c/--commodity-style into a general (reporting) option.

fix: extend application of commodity style to prices (except precision)

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/hledger.m4.md

Combining valuation with filtration is subtle and error-prone (see e.g. #1625).
We have to do in in both MultiBalanceReport and PostingsReport, where it
is done in slightly different ways. This refactors this functionality
into separate functions which are called in both reports, for uniform
behaviour

ref: Add new helper functions journalValueAndFilterPostings(With)?.

---

bin/commitlint

ci: Recognise any commit starting with ‘Merge’ as a merge commit, which

---

bin/hledger-check-fancyassertions.hs

The `Show` instance for the error bundle is not human-readable, `megaparsec` provides a prettyprinter.

; imp: use megaparsec's prettyprinter for assertion parse errors

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs

Replace showPosting with a wrapper around postingAsLines.
The functions textConcat(Top|Bottom)Padded are no longer used anywhere
in the code base, and can be removed if desired.
This produces slightly different output for showPosting, in particular
it no longer displays the transaction date. However, this has been
marked as ‘for debugging only’ for a while, and is only used in
hledger-check-fancy assertions. The output there is still acceptable.

cln: Move posting rendering functions into Hledger.Data.Posting.

---

CONTRIBUTING.md

The "Developer workflows" was moved to the `WORKFLOWS.md` file

Fix the link to the developer workdflows

---

hledger/Hledger/Cli/Commands/Print.hs
hledger/test/print/explicit.test

amounts for --auto generated postings. (Fixes #1276)

fix: print: auto: The print command should always display inferred

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml

pkg: Use maximumBound instead of maximumDef to avoid deprecation

---

hledger-lib/Hledger/Read/CsvReader.hs

Fixes #1183.
This fix is due to @la-wu, but hasn't been submitted. If you want to submit your own PR then I'll happily withdraw this.

fix: csv: Successfully parse empty csv file. (#1183)

---

hledger-lib/Hledger/Data/Balancing.hs
hledger/Hledger/Cli/Commands/Prices.hs
hledger/test/prices.test

Fixes #1736.
The first commit is not strictly needed here to resolve #1736, as the second would also resolve that on its own. However, omitting zero amounts in assignments seems reasonable, and might fix some other bugs which haven't been found yet.

Make automatic price inferral work better with zero total amounts.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/balance/multicommodity.test

We also stop eliding long amounts in balance reports, which has caused a lot of confusion (Fixes #1739).

Introduce multiline balance report display.

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIUtils.hs

This PR adds mouse support to hledger-ui. These should work:
- left click on an account should enter its register
- left click on a register transaction should enter the transaction screen
- mouse wheel/trackpad swipe should scroll the accounts and register screens
- left click on the left-most column or top-most row should return to the previous screen (like the LEFT key)
- if mouse support doesn't work on some terminal/platform, it should at least be harmless (unnoticeable)
Known issues:
- ~There seems to be a bounce issue - sometimes one click has the effect of two.~
- ~I would like to left click on the top or left border to navigate back, but these areas seem unclickable.~

ui: add mouse support

---

hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Stats.hs
hledger/Hledger/Cli/Commands/Stats.md
hledger/Hledger/Cli/Main.hs

CliOpts has a new field, progstarttime_.
Currently the new stats are always printed on stdout, ignoring --output-file/--output-format.

imp: stats: also show run time and throughput

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/test/balance/balance.test

Together with -E, this allows showing a balance for all accounts, both
used and declared. I mainly want this for hledger-ui, but there's no
harm in exposing it in the balance command as well. This is somewhat
consistent with the accounts and payees commands.

feat: bal: with --declared, include all declared accounts

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/hledger-ui.m4.md
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/balance/balance.test
hledger/test/balancesheet.test
hledger/test/incomestatement.test

hledger-ui accounts screen will now show (leaf) declared accounts too.
Based on (and motivating) #1765's balance --declared, the goal is to show a useful list of accounts when all you have is some starter files with account declarations.

imp: ui: accounts screen: also show declared leaf accounts

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/hledger.m4.md
hledger/test/journal/transaction-prices.test

A potential implementation of the proposals in #1177. This is almost certainly not the final behaviour, but I'm putting this up to solicit feedback on a solid proposal. Let me know your thoughts!
This means there will no longer be unbalanced transactions, but will be
offsetting conversion postings to balance things out. For example.
```
2000-01-01
a   1 AAA @@ 2 BBB
b  -2 BBB
```
When converting to cost, this is treated the same as before.
When not converting to cost, this is now treated as:
```
2000-01-01
a                           1 AAA
b                          -2 BBB
equity:conversion:AAA:BBB  -1 AAA
equity:conversion:BBB:AAA   2 BBB
```

Generate conversion postings for priced amounts.

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger/hledger.m4.md

parsers to allow for arbitrary numbers of periods in relative dates.
We now accept smart dates like “in 5 days, in -6 months, 2 quarters ago”.

imp: smartdates: Simplify and generalise the SmartDate constructor and

---

hledger-lib/Hledger/Read/Common.hs
hledger/test/check-commodities.test

imp: check: Do not check commodities for zero amounts with empty

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/balance/budget.test

elided if they have a budget. (Fixes #1800)
This only affects calls with --budget and -E, but not with --no-elide.

fix: budget: Make sure boring parents of unbudgeted accounts are not

---

hledger/hledger.m4.md

Me on the mailing list, after skimming the manual section on `--strict`:
> `--strict` does too much for me, ...
Simon kindly informs me that the check command can run individual checks.
https://groups.google.com/g/hledger/c/l3wPnljbLco/m/BvGYgyBTAwAJ
I went back to the manual and found that `--strict` refers to `check`. I'm not sure how I could miss it. I hope that my small change improves the situation a bit.

Manual: clarify reference from --strict to check

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/test/balance/layout.test

all amounts are zero. (Fixes #1789)

fix: layout: Commodity symbols should be omitted in --layout=bare when

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Activity.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Commands/Stats.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

In particular, `splitSpan` is refactored to make it easier to reason about.

Interval-related refactorings and cleanups

---

Makefile

Previously doctests did not do fast compilation, so a common workflow of `make functest; make doctest` would recompile everything and take along time.

test: Run all tests with --fast compilation, not just functests.

---

hledger-lib/Hledger/Read/JournalReader.hs
hledger/hledger.m4.md
hledger/test/journal/directive-account.test
hledger/test/journal/transaction-prices.test

Previously, you declare an account type with the following format:
account assets  A
This has been deprecated since 1.13, and should now be declared with oneof:
account assets  ; type:A
account assets  ; type:asset

imp!: journal: Remove deprecated account type code syntax from account directives.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/Hledger/Cli/Anon.hs
hledger/Hledger/Cli/Commands/Accounts.hs
hledger/hledger.m4.md
hledger/test/journal/anon.test
hledger/test/query-tag.test

For #1817:
Accounts, postings, and transactions can now all be filtered by the
tags in an account's declaration. In particular it's now possible to
more reliably select accounts by type, using their type: tag rather
than their name:
```
account myasset       ; type:Asset
account myliability   ; type:Liability
$ hledger accounts tag:type=^a
myasset
```
API changes:
A finalised Journal has a new jdeclaredaccounttags field
for easy lookup of account tags.
Query.matchesTaggedAccount is a tag-aware version of matchesAccount.
The current tests, to show how it behaves:
```shell
<
account a   ; type:A
account l   ; type:Liability
account r   ; type:R
account o   ; othertag:
account u
2022-01-01
(r)        1
2022-01-02
(a)        1
(l)        1
$ hledger -f- accounts --declared tag:.
a
l
r
o
$ …
```

feat: queries can now match account tags (#1817)

---

hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Accounts.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/hledger.m4.md
hledger/test/query-type.test

Follow-on from #1817/#1819: because matching account types with `tag:` is inconvenient, this adds the `type:TYPES` query, where `TYPES` is any of the (case insensitive) letters `ALERXCV` (see https://hledger.org/hledger.html#account-types.) This is expected to work appropriately with all commands. It handles types inherited from parents, overridden by children, and inferred from account names, so should be a pretty reliable way to select accounts by type if 1. you have declared account types or 2. you use common english top-level account names. Eg:
$ hledger -f examples/sample.journal bal type:al
$1  assets:bank:saving
$-2  assets:cash
$1  liabilities:debts
--------------------
0
API changes:
Journal has a new jaccounttypes map.
The journalAccountType lookup function makes it easy to …

new type: query for easy matching by account type

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/test/csv.test

fix: csv: Allow unicode in field references for csv. (#1809)

---

hledger-lib/Hledger/Read/Common.hs
hledger/test/account-aliases.test

fix: alias: Allow escaped characters in regular expression aliases.

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-ui/Hledger/UI/RegisterScreen.hs

This results in big speedups in cases when we have many transaction prices, like in examples/10000x1000x10.journal. This can be disabled with the show_costs_ option in ReportOpts.
We tried something like this earlier, and ended up causing problems in hledger-ui (see #1577). I think this avoids that issue, but we should be careful nonetheless.

dev: reg: areg: Strip prices early on in PostingsReport and AccountTransactionsReport, when possible.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Utils.hs
hledger/Hledger/Cli/Commands/Prices.hs
hledger/test/prices.test

total prices. (Fixes #1813)
Also reduce duplication for inferring market prices (previously it was
done separately in both Hledger.Data.Journal and
Hledger.Cli.Commands.Prices), and remove *TotalPriceToUnitPrice
functions, since unit prices cannot represent all total prices.

fix: price: Make sure inferred market prices have the correct sign with

---

hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Register.hs

register is still very slow for large reports, but this at least improves it a bit.
`hledger -f examples/100000x1000x10.journal reg`
master -> this branch
```
794,803,740,896 bytes allocated in the heap						   493,117,386,064 bytes allocated in the heap
80,017,131,248 bytes copied during GC							    74,343,432,976 bytes copied during GC
846,933,760 bytes maximum residency (68 sample(s))					       694,092,872 bytes maximum residency (69 sample(s))
31,580,760 bytes maximum slop							  	31,580,760 bytes maximum slop
2430 MiB total memory in use (0 MB lost due to fragmentation)		  	      1973 MiB total memory in use (0 MB lost due to fragmentation)
Tot time (elapsed)	 Avg pause  Max pause		  				       Tot time (elapsed)  Avg pause  Max pause
Gen  0     770481 colls,     0 par   25.081s …
```

dev: reg: areg: Speed up reg and areg by only aligning to first 1000 items.

---

hledger/Hledger/Cli/Commands/Aregister.md
hledger/Hledger/Cli/Commands/Register.md
hledger/Hledger/Cli/Utils.hs

This has the same performance characteristics for a big decrease in alignment
issues. 1000 postings seems to still put it under the memory bottleneck.

imp: reg: areg: Align to first 1000 postings by default, rather than 100.

---

hledger-lib/Hledger/Read/Common.hs
hledger/test/account-aliases.test

aliases, but otherwise the regular expression handler handles escapes.

fix: aliases: Make sure we can escape forward slashes in account

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/test/journal/valuation2.test

fix: Ensure date2 is used for journal valuation if requested. (#1851)

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/test/csv.test

imp: csv: Give an error if unable to substitute csv templates. (#1803)

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/journal/gain.test

Previously, --cumulative with --gain or --valuechange would produce an
empty report. This fixes this issue to produce a reasonable report.

fix: bal: Allow cumulative gain and valuechange reports

---

BENCHMARKS.md
CHANGELOGS.md
CODE.md
COMMITS.md
CONTRIBUTING.md
DOCS.md
FINANCE.md
ISSUES.md
PULLREQUESTS.md
RELEASING.md
TESTS.md
WORKFLOWS.md

Currently, several pages on the website don't render their tables of contents properly. For instance:
This PR addresses all instances I identified, correcting to:

Fix tables of contents in developer documentation

---

hledger/hledger.cabal

For earlier versions `cabal build -w ghc-9.2` fails with 
```
Hledger/Cli/Commands/Rewrite.hs:144:12: error:
Not in scope: type constructor or class ‘D.Diff’
Module ‘Data.Algorithm.Diff’ does not export ‘Diff’.
|
144 | mapDiff :: D.Diff a -> DiffLine a
|            ^^^^^^
```
and
```
Hledger/Cli.hs:49:37: error:
• Couldn't match expected type: template-haskell-2.18.0.0:Language.Haskell.TH.Syntax.Code
template-haskell-2.18.0.0:Language.Haskell.TH.Syntax.Q
(Either String GitHash.GitInfo)
with actual type: template-haskell-2.18.0.0:Language.Haskell.TH.Syntax.Q
(template-haskell-2.18.0.0:Language.Haskell.TH.Syntax.TExp
(Either String GitHash.GitInfo))
• In the expression: tGitInfoCwdTry
In the Template Haskell splice $$tGitInfoCwdTry
In the first argument of ‘versionStringWith’, namely …
```

hledger: bump lower bounds for Diff and githash

---

hledger-lib/Hledger/Data/JournalChecks.hs
hledger/Hledger/Cli/Commands/Check.hs
hledger/Hledger/Cli/Commands/Check.md
hledger/Hledger/Cli/Commands/Check.txt
hledger/test/errors/README.md
hledger/test/errors/assertions.test
hledger/test/errors/recentassertions.j
hledger/test/errors/recentassertions.test

`hledger check recentassertions` (or flycheck-hledger if you configure it
to run this check) will complain if any balance-asserted account does not have a
(cleared) balance assertion within 7 days before its latest posting.  This aims
to prevent the situation where you are regularly updating your
journal, but forgetting to check your balances against the real world,
then one day must dig back through months of data to find an error.
It assumes that adding a balance assertion requires/reminds you to check the real-world balance.
This won't be true if you auto-generate balance assertions when importing bank data.
However it also requires that the assertion posting is marked cleared, so hopefully
you auto-generate uncleared transactions, and before manually marking them cleared
you will …

check recentassertions

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils/Debug.hs
hledger/Hledger/Cli/Commands/Accounts.hs
hledger/Hledger/Cli/Commands/Accounts.md
hledger/test/journal/account-display-order/1/a.j
hledger/test/journal/account-display-order/1/aa.j
hledger/test/journal/account-display-order/1/b.j
hledger/test/journal/account-display-order/account-display-order.test

This PR fixes #1909 (by renumbering account directives after merging or finalising Journals), and adds some useful debug logging (at levels 2, 5 and 6) of file reading/including and account declaration order. 
- lib: save account directive positions, for troubleshooting (1909)
- imp: at --debug 5, log account declarations info while parsing (1909)
- imp: accounts: at --debug 2, show account declaration positions (1909)
- dev: tests for multi-file account display order (1909)
- fix: fix multi-file account display order; improve file read logging (1909)
- dev: journalFilePath, include: show (unknown) instead of nothing
- dev: lib: hlint improvements
- imp: add a missing space after colon in some debug output

fix multi-file account display order (#1909)

---

Makefile
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/Theme.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UITypes.hs
hledger-ui/Hledger/UI/UIUtils.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
stack.yaml
stack8.10.yaml
stack8.6.yaml
stack8.8.yaml
stack9.0.yaml

Adapt to brick's new API, #1889.
- dev: make ghci[d]-ui: fix/update
- pkg: ui: use/require brick 1.0+ (1889)
- stack: use brick 1.0 with older GHCs also

Support (and require) brick 1.0

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger/Hledger/Cli/Commands/Balancesheet.hs
hledger/Hledger/Cli/Commands/Balancesheetequity.hs
hledger/Hledger/Cli/Commands/Cashflow.hs
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/test/journal/account-types.test

This replaces the old journal*AccountQuery with the new Type query. This
enables uniform treatment of account type, and fixes a subtle bug
(#1921).
Note that cbcsubreportquery no longer takes Journal as an argument.

fix!: cbr: Remove old account type query code. (#1921)

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/hledger.m4.md

Previously, CSV date-times with a different time zone from yours (with or without explicit timezones in the CSV) could give off-by-one dates, because the CSV timezone was ignored.
Now,
1. you can use the `timezone` rule to indicate which other timezone a CSV is implicitly using
2. CSV date-times with a timezone - whether declared by rule or parsed with %Z - are localised to the system time zone (or another set with the TZ environment variable).

feat: csv: new timezone rule; convert zoned date-times to local dates

---

bin/README.md

This pull request adds the [`hledger-utils` Python package](https://pypi.org/project/hledger-utils/) to the docs alongside other hledger-related scripts.

📝 Add hledger-utils with 'hledger edit' to docs

---

hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils/Text.hs
hledger/hledger.m4.md
hledger/test/journal/directive-account.test
hledger/test/journal/parens-in-account-name.test

Currently an account name like "a:(aa)" will not have (aa) unbracketed. However, this seems reasonable since the full name is unbracketed and thus will not be confused with virtual or virtual-balanced posting.
Resolves #1915

journal: Fully unbracket AccountNames in account directives

---

hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-web/Hledger/Web/Test.hs
hledger/test/forecast.test

This takes a shot at #1984. This PR adds source positions for periodic transactions and makes sure references are made to the periodic transaction in transactions generated in forecasts.
@simonmichael I wasn't able to find a nice way to test the full interaction as proposed by @nobodyinperson in #1984. The JSON generated is rather large and it seems unresponsible to put this directly into a `.test`-CLI test. Do you know a clean way to integrate a test with an output file that does not depend on the OS used? Or might it be fine to use the `diff`-fix you proposed in [this issue](https://github.com/simonmichael/shelltestrunner/issues/31)?
I did install and run the print command presented in the issue locally to find that it indeed now contains the correct source positions, referencing the …

journal: json: Add source positions to forecast transactions

---

hledger-lib/Hledger/Read/JournalReader.hs
hledger/hledger.m4.md
hledger/test/journal/directive-account.test

Attempt 2.
Previously, the accounts passed to account directives would be stripped of their surrounding brackets, but the required behaviour is to have account directives plain reject bracketed accounts. This change ensures that accounts in account directives may not start with a bracket character.
Resolves #1915

journal: Account directives reject account names with brackets

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/JournalChecks.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Read/Common.hs
hledger/Hledger/Cli/Commands/Check.md
hledger/hledger.m4.md
hledger/test/journal/costs.test
hledger/test/query-type.test

- lib: add journalMarkRedundantCosts to help with balancing; slight refactoring
- imp: journal: ignore redundant costs; --infer-costs more robustly
- ;doc: journal: redundant costs
- dev: transactionInferCostsFromEquity: clarify partitionPs

infer costs from equity with missing amounts; ignore redundant costs

---

bin/README.md
bin/sortandmergepostings

After mentioning my data entry process [in Matrix chat](https://matrix.to/#/!EPSbhTFKacHmjCdoQb:matrix.org/$b7-H__YJO3hK97jr9YYMjfDWRb8SiRdOCUYm5mTNOK8?via=matrix.org&via=libera.chat&via=gottsnack.net) it occurred to me I've been meaning to see if there was any collection of contrib scripts interested in this bit extracted from some of my other normalization steps.

Add contrib script that can help normalize postings

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Period.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger-ui/Hledger/UI/UIUtils.hs
hledger-web/Hledger/Web/Widget/AddForm.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/hledger.m4.md
hledger/test/balance/intervals.test
hledger/test/cli/report-interval.test
hledger/test/register/intervals.test

Eg,`~ monthly from 1/15` now works, instead of giving an error message or having to rewrite it as `~ every 15th day of month`.
The motivation here was #1962; such periodic transaction rules are one of the things that can prevent hledger reading a Ledger file. Also more generally this limitation just looks a bit arbitrary to users.

imp: journal: periodic txns need not start on an interval boundary

---

hledger/Hledger/Cli/Commands.hs

When there are only few, short strs and width is large, then the div operation in itemspercol would return zero, triggering and error in chunksOf.
This fix makes numcols have always at least as many entries as strs, filling one line.
This specifically happens when having few (e.g., one) extra commands around and just running `hledger` without parameters:
```
$ hledger
hledger: chunksOf, number must be positive, got 0
CallStack (from HasCallStack):
error, called at src/Data/List/Extra.hs:784:26 in extra-1.7.12-5XIucFYKx256evYE8dUSC8:Data.List.Extra
chunksOf, called at ./Hledger/Cli/Commands.hs:282:16 in hledger-1.28.99-8ZdPpZLOhW1Dcld1Fw0yDn:Hledger.Cli.Commands
```

 fix: cli: don't crash multicol with few strings

---

hledger/Hledger/Cli/Commands/Close.md
hledger/Hledger/Cli/Commands/Close.txt

thanks for all the great work in hledger!
i've come across (when looking up the changed in the new release) a duplicate: (the second one has a bit more, and a tiny bit different)
```
The default closing date is yesterday or the journal's end date, whichever is later. You can change this by specifying a [report end date](https://hledger.org/dev/hledger.html#report-start--end-date); the last day of the report period will be the closing date. Eg -e 2022 means "close on 2022-12-31".
The default closing date is yesterday, or the journal's end date, whichever is later. You can change this by specifying a [report end date](https://hledger.org/dev/hledger.html#report-start--end-date); (The report start date does not matter.) The last day of the report period will be the closing date; eg -e 2022 …
```

fix: doc: remove duplicate in `hledger close` docs

---

doc/common.m4
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/TransactionModifier.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Reports/BudgetReport.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/hledger.m4.md
hledger/test/forecast.test
hledger/test/journal/auto-postings.test
hledger/test/journal/costs.test
hledger/test/journal/directive-default-commodity.test
hledger/test/print/explicit.test
hledger/test/rewrite.test

When generating transactions to be saved in the journal, I found the added tags to be too verbose. This PR turns them off by default, and adds a general `--verbose-tags` flag to turn them back on (useful when learning and for troubleshooting).  This affects --forecast, --auto, and --infer-equity.

imp: Generated/modified txns/postings are now tagged only with --verbose-tags

---

examples/sample.timeclock
hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger/hledger.m4.md
hledger/test/timeclock.test

Breaking change: previously timeclock descriptions could contain
semicolons. Now a semicolon in the description will end it and
start a comment (which may contain tags).

timeclock: support comments and tags (fix #1220)

---

hledger-lib/Hledger/Data/Dates.hs

There doesn't seem to be any report code that would hit this bug—just noticed it while working on a script :)

dev: make groupByDateSpan return data when first DateSpan's begin is Nothing

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Posting.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Check.md
hledger/hledger.m4.md
hledger/test/amount-rendering.test
hledger/test/csv.test
hledger/test/journal/parse-errors.test
hledger/test/journal/precision.test
hledger/test/journal/valuation2.test
hledger/test/print/explicit.test
hledger/test/print/print.test
hledger/test/rewrite.test

I noticed that `print` strips the commodity symbol from zero posting amounts, transforming eg `$0` to `0`. This can be awkward when trying to clean up/regenerate a journal, eg. This PR makes print (and print-like) reports preserve the commodity of zeroes more carefully. Other reports like balance and register are expected to work as before, but any additional testing is welcome.
```
print now shows zero posting amounts with their original commodity
symbol and the corresponding style (instead of stripping the symbol).
If an inferred amount has multiple zeroes in different commodities,
a posting is displayed for each of these.
Possible breaking changes:
showMixedAmountLinesB, showAmountB, showAmountPrice now preserve
commodityful zeroes when rendering. This is intended to improve print …
```

imp:print: zero posting amounts are now shown with commodity & style

---

ghc-tags.yaml

Provide a ghc-tags.yaml file to make use of ghc-tags with Hledger easy.
ghc-tags is a standalone tool to replace the formerly-builtto -in ":ctags" feature (and I presume ":etags") in GHCi. These walked over the source and produced a TAGS file (in vim-compatible ctags or Emacs-compatible etags format) that allows the relevant editors to quickly navigate around function definitions.
ghc-tags trips over some of the CPP used in Hledger. The solution is to provide ghc-tags with explicit CPP defines via a YAML file. However, if a YAML file is provided, one also must specify the source paths, as the tool XORs config file | paths-on-command-line.
See <https://github.com/arybczak/ghc-tags/issues/6> for more information.

;dev: Add a ghc-tags.yaml file

---

hledger-lib/Hledger/Read/RulesReader.hs

I'm interested in hledger but really need https://github.com/simonmichael/hledger/issues/2054 for my use-case (certain locations for the same store fit in one purchase category, other locations in another).
I don't know a whole lot of Haskell but hopefully enough to make myself dangerous. I _think_ this change works? The tests I added seem to pass?

feat: CSV rule negation

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/balance/layout.test

Fixes #1012.
Add a flag --only-summary for multi-column balance reports, which only displays the summary columns (--row-total, --average). This is useful when there are many columns (a weekly summary over many years) where you're only interested in the average (or some other summary).

feat: balance: Add only-summary flag (#1012)

---

hledger-lib/Hledger/Data/Json.hs
hledger-web/Hledger/Web/Handler/MiscR.hs

This adds the accounts' declaration info to the `/accounts` endpoint in hledger-web.  My use case is to be able to access account tags in some (unpublished as of now) client-side JS I'm working on.
This does add a new field to `accountsKV` in `Hledger.Data.Json`.  That field can have a value of `Nothing`/`null` if the declaration info hasn't been added.  (I'm doing this in the Web-side code.)
I have compared the output from before and after this commit ([script](https://gist.github.com/s-zeid/05db466eb3158522a0d5f99fdc812663)), and at least for my journal (and some random ones in `/examples/`), there were no changes other than the declaration info being added.
This is my first time working with Haskell, so I apologize if I did this the wrong way or made some other noob mistake.

imp: web: include account declaration info in accounts JSON

---

.sandstorm/launcher.sh
.sandstorm/sandstorm-pkgdef.capnp
hledger-web/Hledger/Web/Foundation.hs
hledger-web/Hledger/Web/Handler/AddR.hs
hledger-web/Hledger/Web/Handler/EditR.hs
hledger-web/Hledger/Web/Handler/JournalR.hs
hledger-web/Hledger/Web/Handler/MiscR.hs
hledger-web/Hledger/Web/Handler/RegisterR.hs
hledger-web/Hledger/Web/Handler/UploadR.hs
hledger-web/Hledger/Web/Import.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger-web/hledger-web.cabal
hledger-web/hledger-web.m4.md
hledger-web/package.yaml
hledger-web/templates/default-layout.hamlet
hledger-web/templates/journal.hamlet
hledger-web/templates/register.hamlet

Changes:
1. rename the sandstorm "manage" permission to "edit" (old permission names: view, add, manage;
new permission names: view, add, edit).
Rationale: "edit" best describes this permission's current powers, to users and to operators. If we ever added more manager-type features we'd want that to be a new permission, not a rename of the existing one (which would change the powers of existing users).
2. rename the sandstorm roles for consistency with permissions (old role names: viewer, editor, manager;
new role names: viewer, adder, editor)
Rationale: it's needed to avoid confusion.
3. add a new option: --allow=view|add|edit|sandstorm (default: add). 'sandstorm' sets permissions according to the X-Sandstorm-Permissions header. Drop the --capabilities and --capabilities-header options. …

imp:web: access control UX cleanups (fix #834)

---

hledger-lib/Hledger/Read/CsvUtils.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Aregister.md
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Balancesheet.md
hledger/Hledger/Cli/Commands/Balancesheetequity.md
hledger/Hledger/Cli/Commands/Cashflow.md
hledger/Hledger/Cli/Commands/Incomestatement.md
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Print.md
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Commands/Register.md
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/hledger.m4.md
hledger/test/balance/budget.test
hledger/test/balance/layout.test
hledger/test/register/csv.test

I've been writing some add-on scripts to analyze my hledger data and frequently wishing I had tsv output. csv is just complicated enough to require a bit of parsing--usually through some external dependency--whereas tsv is trivial enough to decode directly in essentially any environment. (It's also the native and strongly preferred format of [visidata](https://www.visidata.org/).)
I see there's an old issue requesting this feature (#869). There also seems to be an old pull request that circled around it a bit, but never turned into anything.
I believe the implementation is in fact pretty trivial. The data is identical to csv output, so it should just be a matter of writing `printTSV` based on `printCSV` and hooking it up.
A few notes:
- This creates a small amount of code duplication, …

feat: cli: Add tsv output (#869)

---

hledger-lib/Hledger/Read/RulesReader.hs
hledger-lib/Hledger/Utils/Regex.hs
hledger/hledger.m4.md
hledger/test/import/match.csv
hledger/test/import/match.rules
hledger/test/import/match.test

Extend CSV rules handling to support interpolating regular expression match groups into field assignments.
For example. Given a conditional block
if %date (....-..)-..
comment1 date:\1-01
The regular expression includes a region denoted by parenthesis which describe a match group. If the regular expression matches, the field assignment has '\1' substituted for the first match group value from applying the regular expression.
In this example, a date-warping comment is generated, setting the posting's date to the first of the month.
Another example
if %account1 liabilities:jon:(.*)
account1 \1
Here we use the match group to throw away a prefix on account names.
We extend `renderTemplate` to detect and process strings of the form '\N+' (isDigit N). Match groups are scoped to a conditional …

feat: import: interpolate regex matches in field templates (#2009) 

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger/hledger.m4.md
hledger/test/timedot.test

This is another complication to the increasingly inaccurately-named timed format, but it's something I've long wanted for my own time logging:
In place of dots you can write letters, which also generate a tag `t:`
(short for "type") with the letter as its value (and one posting per value).
This provides a second dimension of categorisation, viewable in reports with `--pivot t`.

feat:timedot: tagged time logging with letters

---

hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml

`brick` 2.2 is a minor improvement over 2.1.1, so no API breakages expected. See also https://github.com/simonmichael/hledger/pull/2128#discussion_r1431765057
Builds and tests fine with hledger-ui `1.32.1`.

imp: Support brick 2.2

---

hledger/Hledger/Cli/Commands/Aregister.md
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Balancesheet.md
hledger/Hledger/Cli/Commands/Cashflow.md
hledger/Hledger/Cli/Commands/Incomestatement.md
hledger/Hledger/Cli/Commands/Print.md
hledger/Hledger/Cli/Commands/Register.md
hledger/hledger.m4.md

This draft PR aims to document the version a feature was introduced. As discussed in the Matrix room, `*Added in <version>*` will be prepended to;
1. heading, or if it doesn't exist
2. the description.
For v1.32,
Dropped;

;doc: add version annotations for new features

---

bin/hledger-bar

I [encountered][1] an unexpected error when testing hledger-bar for
proposed inclusion in Homebrew's default installation of hledger:
/opt/homebrew/Cellar/hledger/1.32.2_1/bin/hledger-bar: line 81:
conditional binary operator expected
I'm doubtful that this is fixed by running shellcheck, but checking
a script against shellcheck is usually one of the first things I check
before debugging shell!
This patch is ~generated by shellcheck with
shellcheck --shell=bash --enable=all --format=diff bin/hledger-bar | \
git apply
[1]: https://github.com/Homebrew/homebrew-core/actions/runs/7606843601/job/20713321881?pr=160590

fix: Run shellcheck on hledger-bar

---

bin/hledger-simplebal

Shellcheck handled the variable fixups. The pipefail flag avoids another Shellcheck warning w.r.t. handling pipe failures. This script is so minimal that it's safe to simply fail the pipe entirely if the hledger command fails.
_(Last shellcheck eval unless you're open to more and I find time. Doing these as I prep a PR to include them to be installed by default in the [Homebrew package][1].)_
[1]: https://github.com/Homebrew/homebrew-core/pull/160590

dev: Runs shellcheck on hledger-simplebal

---

hledger-web/static/hledger.css

Super minimal change. Just preserving line breaks in hledger-web. See the following before and after screenshots:
Before:
After:
I was not sure if this would be nice to have in the changelog or not. Let me know if you would prefer me to prefix the commit message with `;`.

fix: css to preserve linebreaks in messages

---

hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Read/RulesReader.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger-lib/Hledger/Read/TimedotReader.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/test/csv.test
hledger/test/ssvtest.sh

With these changes, `hledger` now supports using the `ssv:` and `tsv:` prefixes to determine the file separator. For example:
```
$ cat basic_s
Date;Description;Id;Amount
12/11/2019;Foo;123;10.23
$ cat basic_s.rules
skip         1
fields       date, description, , amount
date-format  %d/%m/%Y
$ hledger print -f ssv:basic_s # stock hledger cannot parse the file
The hledger journal file "/home/michael/builds/hledger/ssv:basic_s" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
$ stack exec -- hledger print -f ssv:basic_s # But this new build can!
2019-11-12 Foo
expenses:unknown           10.23
income:unknown            -10.23
```
Some notes from my end:
* Since I was already poking around this area, I …

imp: Support tsv and ssv prefixes (#2164)

---

bin/hledger-bar

I misread something, and apparently, whatever test I used didn't fail because what's there now is not valid at all.

fix: correct to inherit_errexit in hledger-bar

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs

base 4.19.0.0 introduces Data.List.!? which clashes with Data.Vector.!?, the latter of which is needed for vector operations.
This PR hides Data.List.!? in the relevant locations to prevent the name clash.

fix: Hide ambiguous instance for (!?)

---

hledger-lib/Hledger/Read/RulesReader.hs
hledger/test/csv.test

As discussed in #2181 , it seems sensible to allow comment lines in the "if" table body.
This small patch does just this (and adds a test that demonstrates behaviour).

Allow comment lines in the "if" table body

---

hledger/hledger.m4.md

Explain comments in the table body and matcher application order (related to #2181 )

;doc: explain comments in "if tables" and order of application

---

hledger/Hledger/Cli/Commands/Roi.hs
hledger/test/roi.test

`roi` was initially written when most of the `--value` / `--cost` infrastructure was either absent or in its infancy. As a result, `roi` attempted to do its own very ad-hoc "convert to a single cost" thing -- which is no longer needed, and in fact fails miserably sometimes, as shown by #2190 .
This hopefully makes `roi` interact with `--value`/`--cost` in a more straightforward way.

fix: roi correctly interacts with --value (fixes #2190)

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Period.hs
hledger-lib/Hledger/Reports/ReportOptions.hs

This PR changes how the week name is displayed in the column header by shortening it for all reports, and omitting the year if all column are within the same year.
We rename `showPeriodMonthAbbrev` to `showPeriodAbbrev` as it's now used for weeks too, so not strictly just months.
It adds the following method
```haskell
showPeriodAbbrev (WeekPeriod b) = T.pack $ formatTime defaultTimeLocale "W%V" b
```
and changes the multi-year naming:
```diff
- showPeriod (WeekPeriod b) = T.pack $ formatTime defaultTimeLocale "%FW%V" b
+ showPeriod (WeekPeriod b) = T.pack $ formatTime defaultTimeLocale "%0Y-W%V" b
```

Abbreviate week naming for weekly reports

---

hledger-web/Hledger/Web/App.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger.conf.sample

A followup to https://github.com/simonmichael/hledger/issues/2099, https://github.com/simonmichael/hledger/pull/2100 and https://github.com/simonmichael/hledger/issues/2127. Now relative links to js/css resources will use the same hostname etc. that the main page was requested from, making them work better when accessed via multiple IP addresses/hostnames without an explicit --base-url setting.
Also, --base-url's value must now begin with `http[s]://`; previously it accepted just a hostname, causing bad links.

web: guess a more robust default base url; validate --base-url

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Read/RulesReader.hs
hledger-lib/Hledger/Write/Csv.hs
hledger-lib/Hledger/Write/Html.hs
hledger-lib/Hledger/Write/Ods.hs
hledger-lib/Hledger/Write/Spreadsheet.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/hledger.m4.md

Here is my proposal for an export of balance reports to the formats FODS and HTML.
What I plan to do next:
[ ] Base the CSV export on the same machinery.
[ ] FODS export for multiperiod balances.
[ ] base multiperiod CSV and HTML export on this machinery.
[ ] add a FODS column to the format support matrix in hledger.m4.md
Here are some ideas for further improvements:
[ ] Add hyperlinks to HTML and FODS documents, e.g. an account name could link to an according hledger-web URL. This feature could be enabled by a command-line option like `--anchor-url=http://localhost:5000/`.
[ ] I could make the total sum in FODS a formula. This would show the user what the number means and LibreOffice would recompute the sum if someone edits the balance report there.
[ ] Support for ODS currencies. ODS …

Balance export FODS and HTML

---

hledger-lib/Hledger/Write/Html.hs
hledger-lib/Hledger/Write/Ods.hs
hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Here are some more commits for unifying existing multibalance HTML export with my Spreadsheet data type.
One visible effect is that now FODS tables also get the double lines like the multibalance HTML
and that the formats CSV, HTML, FODS should be transposable for all three kinds of balance exports.
I was also able to remove the dissection of already formated rows in
Commands.Balance.multiBalanceReportHtmlHeadRow, multiBalanceReportHtmlBodyRow, multiBalanceReportHtmlFootRow.
However, there was a comment "TODO pad totals ..." that I do not understand.
It belonged to multiBalanceReportHtmlHeadRow, which is now gone.
Thus the comment is probably no longer at a sensible position if it is still relevant, at all.

Add border and class attributes to Spreadsheet data type

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs

The "Net" row in the HTML output of `balancesheet` formatted amounts using `machineFmt` which is inconsistent with all the other amounts in the balance sheet. This fixes that by formatting Net amounts using `oneLineNoCostFmt`.

fix: amount formatting of the Net row in the balancesheet HTML output

---

hledger-web/Hledger/Web/Handler/RegisterR.hs

Bug was introduced in commit 2a99b3d45634f26cd62745ddce6136361001b3f8 in an effort to get rid of partial List.tail,
because GHC-9.8 started to warn about it.
Problem is that the rewritten code with tailDef always removes the last account, whereas the original intention was to replace all accounts by a comma except the last one. addCommas should prepare a comma separated list like List.intercalate.

web: RegisterR.getRegisterR.addCommas: do not drop last account

---

hledger-lib/Text/Tabular/AsciiWide.hs

I am trying to understand what's going on in `Tabular.AsciiWide.render` and to this end I replace the manual recursive implementation of `renderRs` by using the high level `flattenHeader` function.

lib: Tabular.AsciiWide.renderRs: simplify using flattenHeader

---

hledger-lib/Hledger/Write/Html.hs
hledger-lib/Hledger/Write/Html/Attribute.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Some code cleaning. This way I can use the HTML output helpers in `Write.Html`.

lib: Write.Html.Attributes: extracted HTML output helpers from Cli.Commands.Balance

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Write/Html.hs
hledger-lib/Hledger/Write/Ods.hs
hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/hledger.cabal
hledger/package.yaml

This adds the option `--anchor` to `hledger-cli`. If the user passes this option, then in HTML and FODS output the account and date header cells become hyperlinks to `hledger-web`.
If you like this feature, I add some documentation.
I could also rename the option to `--base-url` for consistency with `hledger-web`.
There is a problem though. Some special characters like `+` or umlauts in account names are not correctly escaped in percent URL syntax by Lucid. I do not know how to solve this correctly with Lucid and whether it is solvable with Lucid, at all.

Add hyperlinks to accounts and dates in HTML and FODS export

---

hledger-lib/Hledger/Write/Html/Blaze.hs
hledger-lib/Hledger/Write/Html/Lucid.hs
hledger-lib/Hledger/Write/Ods.hs
hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

I think this is the best compromise for multibalance:
* In HTML there is only one merged Total cell.
* In CSV there is a Total header in every totals row.
* In FODS the Total header is contained in every row, but only the first one is shown in a merged cell. Formulas can still access the covered Total text e.g. for VLOOKUP.
Same applies to account names in `tidy` layout.

Vertically merge cells showing account names and Total

---

hledger/Hledger/Cli/Commands/Balance.hs

It might appear less readable. In this case we might use the alternating grey bars as in `compoundBalanceReportAsHtml`.

budgetReportAsSpreadsheet: vertically merge duplicate account name cells

---

hledger/Hledger/Cli/Commands/Balance.hs

instead of multiBalanceReportHtmlRows.
This way, HTML output automatically supports transposition.
I'd like to do the same for `multiBalanceReportAsCsv`,
unfortunately it has a special case for LayoutTidy which excludes totals.
You can achieve the same by explicit options, but this would be a user-visible change.

Cli.Commands.Balance.multiBalanceReportAsHtml: now uses multiBalanceReportAsSpreadsheet

---

hledger/embeddedfiles/hledger-journal.md

`hledger/embeddedfiles/hledger-journal.md` was pointing to the non-existing `../../doc/tldr/hledger-journal.md` so this commit removes that dead link.

dev: remove the dead link: hledger/embeddedfiles/hledger-journal.md

---

bin/hledger-balance-as-budget.hs
bin/hledger-check-postable.hs
bin/hledger-check-tagfiles.cabal.hs
bin/hledger-check-tagfiles.hs
bin/hledger-combine-balances.hs
bin/hledger-move.hs
bin/hledger-print-location.hs
bin/hledger-smooth.hs
bin/hledger-swap-dates.hs
hledger/Hledger/Cli/Commands/Balance.hs

I've fixed the compilation errors in all the scripts in bin/
This necessitatied adding `budgetReportAs...` to the export list of Commands.Balance - I think there are no special reasons for them being omitted, as all the other reporting functions are exported.

Fix all scripts in bin/

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Disable total row for LayoutTidy in balance reports. CSV, FODS, HTML are now consistent in this respect.
Correct headings for LayoutTidy in CompoundBalance to CSV, FODS, HTML export, but totals are still shown.
Fixes https://github.com/simonmichael/hledger/issues/2252.

Layout Tidy: no total row

---

hledger-lib/Hledger/Write/Ods.hs
hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Anchor.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/hledger.cabal
hledger/hledger.m4.md
hledger/hledger.txt
hledger/package.yaml

Unified export to CSV, HTML, FODS via Write.Spreadsheet.
Supports --base-url and hyperlinks to hledger-web.
I intended to hyperlink from txnidx to hledger-web/journal page, however, this would require to move Web.Widget.Common.transactionFragment to `hledger` package. It's not super important for now.

Register export to HTML and FODS

---

hledger-lib/Hledger/Data/RawOptions.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils/IO.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-ui/Hledger/UI/Main.hs
hledger-web/Hledger/Web/Main.hs
hledger-web/Hledger/Web/Test.hs
hledger.conf
hledger/Hledger/Cli.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/DocFiles.hs
hledger/Hledger/Cli/Utils.hs
hledger/hledger.m4.md

This is an impactful change, and I value the CLI and easy scriptability. But it has been working well for help output, and I for one am ready for it. Feedback, testing and problem reports welcome.
Doc:
On unix-like systems, when displaying large output in the terminal,
hledger tries to use a pager when appropriate:
the one specified by the `PAGER` environment variable,
otherwise `less` if available, otherwise `more` if available.
The pager shows one page of text at a time, and lets you scroll around to see more.
While it is active, usually `SPACE` shows the next page, `q` quits, and `?` shows more features.
The pager is expected to display ANSI color and text styling if possible.
hledger adds `R` to the `LESS` and `MORE` environment variables to enable this
in `less` (and in its `more` …

feat: use a pager for all large terminal output, not just for help

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/hledger.m4.md
hledger/hledger.txt

some extensions to documentation regarding FODS export
How can I regenerate `hledger.txt`? `just` only lists targets for Haddock generation.
Why is it checked into the Repo, since it seems to be generated?

FODS documentation

---

hledger-lib/Hledger/Write/Ods.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Aregister.md
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

This addresses #2077.
Now I translate `PerPeriod` to `Historical`, since `PerPeriod` is the default. This is a way to have different defaults for `aregister` (Historical) and `register` (Cumulative).

Aregister: support option --cumulative

---

hledger/Hledger/Cli/Commands/Roi.hs

TWR computation works by computing the running total of "investment units" and their cost. If at some point we run out of units, we could divide by zero trying to compute new cost. Instead lets just reset the cost the the initial one as we have essentially went to the initial state (no units on hand, cost is an arbitrary chosen number 100).
This fixes #2281

lib: fix division by zero in roi when all assets are sold (fixes #2281)

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/UIScreens.hs
hledger-ui/Hledger/UI/UIState.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/hledger.m4.md
hledger/test/balance/depth.test

Previously depth-limiting was universal across all accounts, e.g. all
accounts are clipped to depth 2. However, sometimes you want certain
accounts clipped to a different depth than others, e.g. all expenses to
depth 3, while all assets to depth 2. This commit enables depth-limiting
to optionally include a regular expression, which limits the accounts it
applies to.
More than one depth limit can be passed, and they are applied to each
account name by the following rules:
- If one or more regular-expression depth limit applies, use the
smallest one
- If no regular-expression depth limits apply, and a flat depth limit is
supplied, use that
- Otherwise, do not do any depth limiting
For example, this will clip all accounts matching "assets" to depth 3,
all accounts matching "expenses" to …

Regular-expression limited depth limits

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils/IO.hs

error' and usageError now redden and bolden the first line of error
messages, when ANSI codes are supported and permitted.
And warn goldens and boldens the first line of warning messages.

imp:cli: show first line of error messages in red

---

bin/hledger-git

Instead of manually checking for a .git directory, ask git to check whether
or not we are in a work tree using 'git rev-parse --is-inside-work-tree'.
This takes care of things like being in a subdirectory of a work tree, or
someone having GIT_DIR pointing somewhere other than .git, etc.

;bin: git: make ensure_git more robust

---

hledger/Hledger/Cli/Commands/Roi.hs

Fixes #2316 
`roi` computes returns per each reporting period, and then computes overall return for complete report interval.
When there is just one reporting period, there is no need to compute overall return as it would be exactly the same.
Lets optimize for this.

;roi: optimize "one period per report interval" case a bit

---

hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-lib/test/unittest.hs
hledger/test/unittest.hs

When running `cd hledger-lib && ghci test/unittest.hs`, ghci complains with:
```
test/unittest.hs:7:1: error:
Could not find module ‘Hledger’
It is not a module in the current program, or in any known package.
|
7 | import "hledger-lib" Hledger (tests_Hledger)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
```
I suspect the "hledger-lib" package-qualified import isn't really necessary anymore. After removing it, above ghci command works as expected.
This instance of PackageImports was introduced in commit c7574b8005a84c6116a2871313ce8417b492a823 (2019).

;cln: unittest.hs: remove bothersome PackageImports

---

hledger-lib/Hledger/Read/RulesReader.hs
hledger/hledger.m4.md

If blocks and If tables now allow multiple matchers on the same line. The only requirement is that the first (n-1) matchers end with a '$' (i.e. end of string marker).
Example `if block` with two matchers on the same line:
if %date ^2025-02-22$ & %description amazon
account2 expenses:books
Example `if table` with two matchers on the same line:
if|account2
%date ^2025-02-22$ & %description amazon | expenses:books
I make heavy use of `if tables`.  Example:
```
if|account2|comment2
%description ^CARTE ../../.. AUCHAN SUPERMAR 4 CB | expenses:food:supermarket|
%description ^CARTE ../../.. CARREFOUR.FR CB | expenses:food:supermarket|
...
```
But then sometimes I need to match 2 separate fields, usually `%date` and `%description`, and  I will have to fall back to using an `if block`:
```
if …
```

feat: csv: allow multiple matchers on the same line

---

hledger/Hledger/Cli/CliOptions.hs

While looking at `Hledger.Cli.CliOptions`, I noticed a couple of bits of dead
code which are duplicated elsewhere. I propose we remove them
- `debugArgs`:
A variant of it is present as a local definition in `getHledgerCliOpts'`
- `widthFromOpts`:
As noted in 5c289ac, it is unused elsewhere, and `registerWidthsFromOpts` is right next to it and implements nearly the exact same logic

Hledger.Cli.CliOptions: Remove commented-out, unused functions

---

hledger/Hledger/Cli/Commands/Run.hs

If forecast start and end dates are explicitly requested with --forecast=, those parts of the reportspan_ can be replaced with the forecast dates, meaning more successful cache hits.

imp run: More successful cache hits with forecast

---

hledger-lib/Hledger/Data/Timeclock.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Read/TimeclockReader.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/hledger.m4.md
hledger/test/errors/tcclockouttime.test
hledger/test/errors/tcorderedactions.test
hledger/test/timeclock.test

As requested in #2141, this adds support for having multiple sessions clocked in. These are paired by account name if given on the out entry, and otherwise an out closes the most recent in entry.
Note that this breaks some backwards compatibility, in that we previously ignored the description on the clock out entry.
(Also, I tried to update the documentation with `Shake manuals`, but that seems to have made lots of other changes...not sure if I didn't do something correctly or if those files were just out of date.)

feat: timeclock: Add support for multiple clocked in sessions (#2141)

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-ui/Hledger/UI/UIScreens.hs
hledger/Hledger/Cli/Commands/Aregister.hs

The `aregister` report always abbreviates "other accounts" in the transaction by taking just the first two characters of all account components but the last one. Thus `asset:cash:bank:checking` always becomes `as:ca:ba:checking`. This is a reasonable strategy when outputting to text/terminal, as space is likely to be limited, but is less useful when outputting to machine-readable formats (CSV, HTML, FODS, etc).
- Do not turn "other accounts" into a comma-delimited string when the report is constructed, but pass `AccountName`s up to the caller. This requires modifying the `AccountTransactionsReportItem` type to contain `[AccountName]` rather than `Text`.
- Move the account name summarization (`Hledger.Data.AccountName.accountSummarizedName`) closer to the rendering of the report, so that …

imp: areg: Do not abbreviate other accounts in machine-readable output (#1995)

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/test/balance/budget.test

Budget reports will now respect the --summary-only flag.

fix: budget: Respect --summary-only flag. (#2443)

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/balance/no-total-no-elide.test

Zero rows with --no-elide should only be displayed if either --empty is called or they have non-zero children at some depth.

fix: balance: Don't display zero rows with --no-elide (#2454)

---

hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
stack92.yaml.old
stack94.yaml.old
stack96.yaml
stack98.yaml

On modern gccs, this sometimes causes build failures, see
https://github.com/gregorycollins/hashtables/issues/97

Forbid solving for hashtables 1.3

---

hledger-ui/Hledger/UI/Main.hs
hledger-ui/hledger-ui.m4.md

Not all editors trigger the `Modified` event for files because they don't edit the bits of an existing file, they flush their internal buffer to a new temporary file, then clobber the existing file on disk. This means many editors trigger the `Added` event even when saving changes to an existing journal file.
Tested with `gedit`.
Closes #1617

Help ui --watch catch changes from editors that overwrite files
