simonmichael/hledger

hledger-web/static/hledger.js

http://demo.hledger.org/journal gives some javascript errors, these prevent showing the nice chart and kb shortcuts from working

hledger-web: Set default javascript parameter values in the functions addformReset, addFormShow

---

site/step-by-step.md

minor copyedits

---

site/index.md

Only indent when the display is landscape and wide enough.  #324

Website: Change indent styles to fit smaller screens

---

extra/hledger-rewrite.hs

Compiles and works now. However the --help doesn't seem to work - it shows the whole hledger help rather than the help for this specific command, not sure how that works.

Fix up hledger-rewrite to work with Megaparsec

---

doc/lib.m4
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Utils.hs
hledger/hledger.cabal
hledger/package.yaml

Anon feature

---

extra/hledger-equity.hs

- Make it compatible with current `BalanceReportItem`
- Make multi-commodity postings to be a valid journal entries

Fix hledger-equity

---

bin/hledger-equity.hs
hledger-lib/Hledger/Data/Transaction.hs
tests/misc/amount-rendering.test

- Make output of print to be a valid journal
- Partially reverts 419f5f2a2
Fixes simonmichael/hledger#465

Ensure showTransaction produce a valid journal

---

hledger-ui/Hledger/UI/Main.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
stack.yaml

Updated hledger-ui to use brick-0.16

---

hledger-ui/Hledger/UI/Main.hs
hledger-ui/hledger-ui.cabal

I hope I didn't break backwards compatibility with older versions ... I tried not to. :-)

hledger-ui: add support for brick 0.17 and vty 0.15

---

hledger-lib/Hledger/Data/AccountName.hs

Escape account names

---

tests/balance/balance.test
tests/cashflow/cashflow.test
tests/incomestatement/incomestatement.test

These pass the current version of hledger available on homebrew and
cover the bug reported in #514 and fixed in #515.

Add balance/cashflow/incomestatement shelltest

---

hledger/Hledger/Cli/Balance.hs
hledger/Hledger/Cli/BalanceView.hs
hledger/Hledger/Cli/Balancesheet.hs
hledger/Hledger/Cli/Cashflow.hs
hledger/Hledger/Cli/Incomestatement.hs

This format seemed the most natural to me, but let me know if this makes sense.
~~~
2017/01/01 * Paycheck
assets:bank:checking             $6000
assets:bank:savings              $4000
income:work
2017/01/02 * Ice Cream
expenses:dessert        $5.50
liabilities:visa
2017/02/01 * Paycheck 2
assets:bank:checking             $3000
assets:bank:savings              $2000
income:work
2017/02/02 * Fancy Dinner
expenses:food                 $20.00
liabilities:american express
~~~
And:
~~~
$ hledger balancesheet -M
Balance Sheet
||  2017/01/31  2017/02/28
==============================++=========================
Assets                       ||
------------------------------++-------------------------
assets:bank:checking         ||    $6000.00    $9000.00
assets:bank:savings          ||    $4000.00 …

Multicolumn reports for bs/cf/is, and -T/-A support

---

hledger/Hledger/Cli/BalanceView.hs

Ongoing fixes (and documentation) to issues mentioned in the final messages of PR #518

Ongoing fixes to bs/cf/is reports

---

hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml

It builds and works fine here.

Allow vty 5.16

---

bin/hledger-budget.hs

Fixes simonmichael/hledger#615

Adapt to CliOpts re-factoring in e3c4a761 to fix #615

---

bin/hledger-budget.hs

This is preparation to make it part of of hledger.

bin: budget: re-factor to use hledgerCommandMode

---

site/investments.md

As discussed in https://github.com/simonmichael/hledger/issues/624.
I have only checked the markdown output on github.

Docs investment guide

---

tests/misc/equity.test
tests/misc/prices.test
tests/misc/rewrite.test

Fix shell-tests for add-ons that became built-in commands.

test: equity/prices/rewrite now builtin

---

doc/lib.m4
hledger-lib/hledger_journal.m4.md
hledger/Hledger/Cli/CliOptions.hs
hledger/hledger_balance.m4.md

Document periodict transactions and automated posting rules along the way.
Link in budgeting-and-forecasting.

Add docs for --auto, --forecast, --budget

---

.gitignore

ignore aes key

---

site/index.md

fix #692.
I did not see a div with that class on http://hledger.org/hledger-web.html or in the markup so figure it is safe.

remove unused style

---

hledger-lib/hledger_journal.m4.md
hledger/hledger.m4.md
site/contributing.md
site/doc/1.5/hledger.md
site/doc/1.5/journal.md
site/doc/1.5/manual.md
site/index.md

Update references to the FAQ in the documentation and on the web site.

doc: update references to the faq

---

hledger-lib/Hledger/Read/JournalReader.hs

This improves the parse error obtained from the following file.
```
$ cat fuel.ledger
2018/04/01 * Fuel
Expenses:Auto:2018:Fuel         51.170 gallons $1.999
Assets:Cash:Wallet
```
Before:
```
$ hledger -f fuel.ledger bal
hledger: /home/simon/finance/fuel.ledger:2:5:
unexpected 'E'
expecting newline
```
After:
```
$ hledger -f fuel.hledger bal
hledger: /home/alex/personal/hledger/fuel.hledger:2:52:
unexpected '$'
expecting ';' or newline
```

lib: restrict backtracking when parsing postings (#747)

---

hledger-lib/Hledger/Read/Common.hs

Fix doctest error introduced by 49c8c093acf8fd212f1e78561969792238f00fae.

Fix doctest error. 

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Utils.hs
stack-ghc8.0.yaml

GHC 8.0 compatibility

---

hledger-lib/Hledger/Read/JournalReader.hs

Parse comments at beginning of periodic transactions.

---

hledger-lib/Hledger/Read/Common.hs

Fix backwards incompatibility with megaparsec 5 (#775)

---

hledger-api/hledger-api.cabal
hledger-api/package.yaml
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/TransactionModifier.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/Hledger/Utils/Debug.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger-lib/hledger-lib.cabal
hledger-lib/hledger_journal.5
hledger-lib/hledger_journal.info
hledger-lib/hledger_journal.m4.md
hledger-lib/hledger_journal.txt
hledger-lib/package.yaml
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
hledger-web/Hledger/Web/Application.hs
hledger-web/Hledger/Web/Main.hs
hledger-web/hledger-web.cabal
hledger-web/package.yaml
hledger/Hledger/Cli/Commands/Balancesheet.hs
hledger/Hledger/Cli/Commands/Balancesheetequity.hs
hledger/Hledger/Cli/Commands/Cashflow.hs
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/Hledger/Cli/Commands/Rewrite.hs
hledger/Hledger/Cli/Utils.hs
hledger/hledger.cabal
hledger/package.yaml
tests/misc/rewrite.test

This continues some cleanups already in master. I had to change a test, but I think it's doing the right thing ?

more auto posting/transaction modifier cleanups

---

hledger-lib/Hledger/Read/JournalReader.hs

raise error on recursive includes

---

hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Roi.hs
hledger/hledger.cabal
hledger/hledger_commands.m4.md
hledger/package.yaml
tests/misc/roi.test

This pull request integrates [hledger-roi](https://github.com/adept/hledger-roi) into hledger.
Command name is "roi" following discussion on IRC.
It comes with moderate-length --help with the potential to expand further on the wiki.

Return on investment

---

site/index.md

Remove Twitter Section of Site

---

hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils.hs
tests/journal/include.test

fixes simonmichael/hledger#896

lib: fix home path expansion in includes

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs
tests/balancesheet/balancesheet.test

This fixes #907 
Test included

cli: compoundbalancecommand will keep zero-balance accounts with children

---

hledger-lib/Hledger/Data/Transaction.hs
tests/journal/parse-errors.test

Partially address simonmichael/hledger#904

lib: include source info in txn balance errors

---

hledger-lib/Hledger/Data/Transaction.hs
hledger-ui/Hledger/UI/ErrorScreen.hs

ui: support all results of showGenericSourcePos

---

hledger-lib/Hledger/Read/JournalReader.hs

I dont know why periodic txn parser was rather different from regular txn parser in the part that parses code/status/desc/comments, but if these differences are eliminated, then it fixes #942 .

lib: fix parsing of status/code/desc/comments in period txn

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/hledger_balance.m4.md
tests/balance/transpose.test

This implements balance --transpose for text and csv outputs, potentially closing #955 
People braver than me could implement it for HTML as well :)

cli: added --transpose to "balance" command

---

.dockerignore
Dockerfile
docker/README.md
docker/start.sh

This adds in-tree Dockerfile that one can use to do hledger development and/or run hledger in contained.
docker/README.md is quite minimal, but on the other hand it is rather hard to write one assuming no
knowledge about docker -- i am not sure where to aim.

package: added Dockerfile

---

docker/README.md
docker/build-dev.sh
docker/build.sh
docker/run.sh

Helper scripts for building and running docker image

Docker scripts

---

hledger-ui/Hledger/UI/UIOptions.hs
hledger/Hledger/Cli/Commands/Accounts.hs
hledger/Hledger/Cli/Commands/Add.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Checkdates.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Import.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Commands/Tags.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Reduce simple lambda expressions

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md
tests/csv/csv-read.test

CSV parser: balance1 and balance2

---

CONTRIBUTING.md

This site has been down for a while it seems.

rm ircbrowse.net log link

---

tests/cli/report-interval.test

I splitted #1009 
This PR can be merged because it only contains a working test for an existing feature.

Add CLI tests for report interval

---

hledger-lib/Hledger/Reports/AccountTransactionsReport.hs

I find the report function less convolved without the integrated recursion.

lib: accountTransactionsReportItems: rewrite using catMaybes and mapAccumL

---

CONTRIBUTING.md
hledger-api/hledger-api.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Prices.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReports.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-web/Hledger/Web/Handler/MiscR.hs
hledger-web/Hledger/Web/Json.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Prices.hs
hledger/hledger_options.m4.md

Seems to work, more testing welcome. I'll merge this soon unless anyone has suggestions.
This is for #131. The docs can be viewed [here](https://github.com/simonmichael/hledger/blob/8d665ecc9f98c22ae8ec9a4db9f408c137877121/hledger/hledger_options.m4.md#valuation).

allow specifying valuation commodity, add -X

---

doc/common.m4
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Main.hs
hledger/hledger_options.m4.md
shell-completion/hledger-completion.bash
tests/cli/date-options.test

Date options for begin and end of time period have problems (see below).
This PR provides tests and aims to fix the problems.

Bugfix, CLI tests and doc for date options (begin/end of time period)

---

hledger-install/hledger-install.sh

update resolver to lts-13.27 for freebsd12

---

hledger-web/static/hledger.js

Weeks in date picker start from Mondays (fix for #1109)

---

hledger-lib/Hledger/Read/CsvReader.hs

I believe that this fixes #1113 
Now code truly does what docs say: balance is an alias to balance1, amount is an alias to amount1, etc, etc. Less code, cleaner code.

Better resolution of csv field aliases ("balance" vs "balance1", etc)

---

hledger/Hledger/Cli/Anon.hs
hledger/Hledger/Cli/Utils.hs
hledger/hledger.cabal
hledger/package.yaml
tests/journal/anon.test

This fixes account anonymization ( #901 ) and transaction code.
_(here was a big banner)_

Fix some missing anonymization

---

hledger-lib/Hledger/Read/Common.hs
hledger-web/static/js/excanvas.js
hledger/CHANGES.md
hledger/hledger.1
hledger/hledger.info
hledger/hledger.txt
hledger/hledger_options.m4.md

These should all be non-semantic spelling fixes.

Fix some simple typos

---

hledger-lib/Hledger/Read/CsvReader.hs
tests/csv.test

This fixes #1111 and adds support for balanced virtual posting generation as well.

lib: support generation of (un)balanced virtual postings in csv reader

---

hledger-lib/Hledger/Query.hs

`compareMaybeDates` is equivalent to `compare` due to the Ord instance for Maybe a. Finding the smallest/largest elements of a list is probably best done with `minimum` and `maximum` rather than sorting and taking the head.

Simplify date comparison code.

---

hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils.hs
hledger-lib/Hledger/Utils/Test.hs
hledger-web/Hledger/Web/Widget/AddForm.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Add.hs

lib: Replace some utility functions with library functions.

---

examples/csv/ynab-web-register.csv.rules

Was looking around examples and saw an outdated example for YNAB, decided to add a rules file that works for the latest export.

Add rules example for the new YNAB Web csv export format

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs

It looks like in the process of pruning the old BalanceReport code, the function unifyMixedAmount is no longer exported. Since I find this function useful in other contexts, I thought it might be useful to move it to Data.Amount and make it return a Maybe.

lib: Move unifyMixedAmount to Hledger.Data.Amount.

---

hledger/Hledger/Cli/Commands/Accounts.hs
tests/accounts.test

cli: Get --drop working in account --tree

---

hledger-lib/Hledger/Reports/BalanceReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
tests/balance/sorting.test

lib: Use last column of historical balance as total for (multi)balanceReport.

---

hledger-lib/Hledger/Data/Amount.hs

I'd appreciate a second set of eyes on this. I believe the rewriting of amountLooksZero is equivalent to the previous one, but is much simpler and faster. Since amountLooksZero is called whenever you normalise a mixed amount, which happens quite a lot, this actually seems to have a small but noticable effect on performance. However, the original definition was a bit convoluted, so I may have missed some edge cases.
I've also cleaned up normaliseHelper a bit. Previously it would check to see if there were any zero amounts with empty commodity, and if there were it would return the last zero amount, even if it had an empty commodity. It now returns the last zero amount with nonempty commodity, which I believe was the intended result.

lib: Speed up amountLooksZero.

---

hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-ui/Hledger/UI/Main.hs
hledger/Hledger/Cli/Commands/Accounts.hs

lib: Make queryDepth return Maybe Int.

---

hledger-lib/Hledger/Data/Commodity.hs
hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/PeriodicTransaction.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/JournalReader.hs
hledger-lib/Hledger/Utils/Text.hs
tests/journal/posting-dates.test

lib: Refactor some parsers

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
tests/balancesheet.test

lib: Filter starting balances by subreport query in compoundBalanceReportWith.

---

hledger-lib/Hledger/Utils/String.hs

Replaced an incorrect use of `takeWhile1P` with `takeWhileP`. Addresses #1345.

lib: Correctly strip ansi sequences with no numbers/semicolons.

---

hledger-lib/Hledger/Query.hs

Export OrdPlus, remove un-necessary GHC pragma

---

hledger-web/hledger-web.cabal
hledger-web/package.yaml

Slashes need to be escaped or they introduce unexpected italic style due to Haddock markup.

Fix hledger-web description

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportTypes.hs
hledger/Hledger/Cli/Commands/Balancesheet.hs
hledger/Hledger/Cli/Commands/Balancesheetequity.hs
hledger/Hledger/Cli/Commands/Cashflow.hs
hledger/Hledger/Cli/Commands/Incomestatement.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

This exports a few helper functions and generalises compoundBalanceReport to make them a bit more useful for writing your own custom balance reports.

Export multiBalanceReport helper functions and generalise compoundBalanceReport.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Types.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/hledger_csv.m4.md
tests/csv.test

- cleanup
- ;csv: refactor amount parsing
- csv: decimal-mark rule to help with number parsing

csv decimal mark

---

hledger/Hledger/Cli/Commands/Roi.hs

cli: improve error for roi IRR rootfinding problems (closes #1398)

---

hledger/Hledger/Cli/Commands/Roi.hs
hledger/Hledger/Cli/Commands/Roi.md

roi: add adept's IRC discussion to doc

---

hledger-lib/Hledger/Data/Journal.hs
hledger/hledger.m4.md
hledger/test/journal/valuation.test

Addresses #1405.
Let me know what you think of these changes.

lib: Include price directives when calculating journal end date.

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger-lib/Hledger/Utils/Text.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Register.hs

lib: Make sure to add a newline to the end of aregister report.

---

hledger/test/csvtest.sh

As discussed in IRC. Should probably be tested by someone on BSD by running `make functest`.

make csvtest.sh script POSIX and shellchecked

---

hledger-lib/hledger-lib.cabal
hledger-ui/hledger-ui.cabal
hledger-web/Hledger/Web/Foundation.hs
hledger-web/Hledger/Web/Handler/RegisterR.hs
hledger-web/Hledger/Web/Widget/Common.hs
hledger-web/hledger-web.cabal
hledger-web/static/hledger.js
hledger-web/templates/chart.hamlet
hledger-web/templates/register.hamlet
hledger/hledger.cabal

By dragging a region with the mouse

Allow selecting the date range from the chart

---

hledger/Hledger/Cli/Commands/Roi.md

This:
1. Explains the semantincs of `--inv` and `--pnl` and how roi is using them
2. Mentions that roi supports --value/--cost and friends
3. Move lengthy Snake Oil example to the Cookbook

roi: cmdline help simplified

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/journal/valuechange.test

Fix --valuechange for CompoundBalanceReport.

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/test/journal/valuation.test

Reinstate support for --value=cost,COMM

---

hledger-web/hledger-web.txt
hledger/embeddedfiles/hledger_csv.5
hledger/embeddedfiles/hledger_csv.info
hledger/embeddedfiles/hledger_csv.txt
hledger/embeddedfiles/hledger_journal.5
hledger/embeddedfiles/hledger_journal.info
hledger/embeddedfiles/hledger_journal.txt
hledger/embeddedfiles/hledger_timeclock.5
hledger/embeddedfiles/hledger_timeclock.info
hledger/embeddedfiles/hledger_timeclock.txt
hledger/embeddedfiles/hledger_timedot.5
hledger/embeddedfiles/hledger_timedot.info
hledger/embeddedfiles/hledger_timedot.txt
hledger/hledger.txt

They are not cleaned up in 9824c9683ae80a2ebd5be72b8dad88f00c8588bd

Remove more reference to old man page stuff

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/test/balance/balance.test

lib: Properly escape quotes in csv output.

---

hledger-lib/Hledger/Reports/BudgetReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Fix html report headers for compound balance report.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/test/journal/transaction-prices.test
hledger/test/journal/valuation.test

Strip prices from balance and register commands if unneeded.

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Text/WideString.hs

add a Show instance for AmountDisplayOpts, WideBuilder

---

hledger-web/hledger-web.cabal
hledger-web/package.yaml

Builds fine and all tests pass here.

Allow yesod-form 1.7

---

hledger-ui/Hledger/UI/UIOptions.hs
hledger-web/Hledger/Web/WebOptions.hs
hledger/Hledger/Cli/Main.hs
hledger/Hledger/Cli/Version.hs
hledger/hledger.cabal
hledger/package.yaml

One possible solution to #1539.

cli,ui: Include full binary name and git hash in program version.

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/test/balance/drop.test
hledger/test/balancesheet.test

cli: Make sure full account name is used (possibly including dropping) for csv output (#1566)

---

hledger-ui/Hledger/UI/Editor.hs

I tested this with hledger-ui. hledger-ui opened kakoune at the desired lines when I pressed `E`.
I don't yet know how to make hledger-ui open a file at the last line on kakoune.

Add support for kakoune editor

---

hledger-ui/Hledger/UI/Editor.hs

I tested it with emacs(client), nano, vscode, kakoune, nvim, and vis.

Improve editor support

---

hledger-ui/hledger-ui.info
hledger-ui/hledger-ui.m4.md
hledger-web/hledger-web.info
hledger-web/hledger-web.m4.md
hledger/hledger.info
hledger/hledger.m4.md

This should solve #806. Thanks to @simonmichael for all the help.

Add dir section to info file

---

examples/systemd/hledger-web.service
examples/systemd/hledger.nginx
examples/systemd/readme.md

This commit contains example files for a hledger-web systemd service and the basics for an nginx reverse proxy.

;imp: added systemd and nginx files to examples dir

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/push.yml
.github/workflows/windows.yml
bin/commitlint

This is imperfect but better than nothing, and should avoid
spurious failures on force pushes to PRs.

ci: commitlint: when range is invalid (force push), check last 20

---

hledger/Hledger/Cli/Commands/Roi.md
hledger/hledger.m4.md

I think this should cover the topics we discussed in #1609 (and thus close it)

Provide more verbose advise on complex quoting use-cases highlighted in #1609

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger/test/journal/amounts-and-commodities.test
hledger/test/register/related.test

Addresses #1625, #1629, and #1630.

Various fixes for combining transaction filtering with valuation.

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml

Implement the lenses for ReportOpts and ReportSpec as discussed in #1545.

dev: lens: Introduce lenses for ReportOpts and ReportSpec.

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/EntriesReport.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/PostingsReport.hs
hledger-lib/Hledger/Reports/TransactionsReport.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/aregister.test
hledger/test/journal/amounts-and-commodities.test
hledger/test/journal/auto-postings.test
hledger/test/register/related.test

Cherry-picking #1631 fixes for 1.22

---

hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Query.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Reports/AccountTransactionsReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-web/Hledger/Web/Test.hs
hledger/Hledger/Cli/CliOptions.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/forecast.test

Cherry-picking #1639 for 1.22-branch

---

hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/Commands/Balance.md
hledger/Hledger/Cli/CompoundBalanceCommand.hs
hledger/test/journal/gain.test

This is an adaptation of @chvp's PR #1432 to the new valuation framework. (Sorry for submitting a new PR).
Before we merge we need more tests, and in particular we need to decide on:
- the behaviour when there's no cost but changing valuation
- the behaviour with different valuation modes
- some tests for compound balance reports

Implement gain report for balance reports.

---

hledger-lib/Hledger/Data.hs
hledger-lib/Hledger/Data/Dates.hs
hledger-lib/Hledger/Data/Types.hs
hledger/hledger.m4.md
hledger/test/forecast.test

Possible implementation for https://github.com/simonmichael/hledger/issues/1517

New periodic expressions for every weekday et al

---

hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Json.hs
hledger-lib/Hledger/Data/Types.hs

Also clean up some outdated or inaccurate comments.

cln: Derive more instances in Hledger.Data.Types to reduce orphans.

---

hledger/Hledger/Cli/Commands/Roi.hs

Recent discussion on the mailing list uncovered a rare corner-case bug in `roi` which will manifest itself when someone tries to apply the PnL to the investment at the same date as it is "opened" (initially funded).
Roi applies the PnL (changes the valuation of the investment) before applying fundings/withdrawals, when they fall on the same date. This does not work when investment is still empty and PnL transaction is applied prior to the initial funding transaction.
Fix makes sure that TWR computations for the empty investment never start from applying PnL.

fix: roi: rare bug with PnL applied on the first day of investment

---

bin/hledger-balance-as-budget.hs
bin/hledger-check-fancyassertions.hs
bin/hledger-combine-balances.hs
bin/hledger-smooth.hs
bin/hledger-swap-dates.hs

Fixes #1464.
Also fixes #1108.

Get hledger-check-fancyassertions working again.

---

hledger-web/Hledger/Web/Widget/AddForm.hs

fix: web: Handle non-regular postings in the add transaction form. (#1058)

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIOptions.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-ui/Hledger/UI/UITypes.hs

Pulls all the UI options into UIOpts, removes a redundant option, and uses the power of lenses to significantly simplify UIState.hs.

Cleanup UIOpts and UIState

---

doc/common.m4
hledger/Hledger/Cli/CliOptions.hs

imp: cli: Let --today option handle smart dates, determined relative to

---

hledger-lib/Hledger/Reports/PostingsReport.hs

Fixes #1683, maybe?
When accidentally called with a large number of intervals, PostingsReport is very inefficient (complexity looks to be `O(p*i)`, where `i` is the number of intervals and `p` is the number of postings. This improves this to `O(p*log(i))`, where `i` is the number of intervals which actually have postings in them (or all intervals if called with `--empty`).
This also improves the efficiency of `splitSpan`, requiring about half as many date calculations.

Improve efficiency of PostingsReport when called with many intervals

---

hledger-lib/Hledger/Data/Account.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Utils/Parse.hs

Minor cleanups to reduce module dependencies, and make export lists explicit.

Module cleanups

---

hledger/Hledger/Cli/Commands/Print.hs

imp: csv: sql: Use . as a decimal point in sql output for Print

---

hledger-lib/Hledger/Reports/ReportOptions.hs

cln: Display friendly error message if --pretty is given an incorrect

---

hledger/Hledger/Cli/Main.hs

--forecast) to be moved after the subcommand name.

imp: cli: Allow general optional argument flags (--pretty and

---

examples/all.journal
examples/current.journal
hledger/Hledger/Cli/Commands.hs
hledger/test/journal/include.test

Also include a test which makes sure !include is still parsed.

cln: Replace all uses of deprecated !include with include.

---

hledger-lib/Hledger/Data/AccountName.hs
hledger-lib/Hledger/Data/Amount.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Utils/String.hs
hledger-lib/Hledger/Utils/Text.hs
hledger-lib/Text/Tabular/AsciiWide.hs
hledger-lib/Text/WideString.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
stack.yaml
stack8.10.yaml
stack8.6.yaml
stack8.8.yaml

Use doclayout for text length calculations.

---

hledger-lib/Hledger/Read/CsvReader.hs
hledger/test/csv.test

fix: csv: Handle multiple zero amounts in postings in csv files. (#1733)

---

hledger-lib/Hledger/Reports/MultiBalanceReport.hs
hledger/test/balance/depth.test

values, not zero everywhere. (Fixes #1761)

fix: balance: Balance reports with --depth=0 should report on true

---

hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-ui/Hledger/UI/UITypes.hs
hledger-ui/Hledger/UI/UIUtils.hs

silently ignoring. (Fixes #1394)

imp: ui: Display an error message on invalid regexp, rather than

---

hledger-lib/Hledger/Data/Journal.hs
hledger-lib/Hledger/Data/Posting.hs
hledger-lib/Hledger/Data/Transaction.hs
hledger-lib/Hledger/Data/Valuation.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Read/InputOptions.hs
hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIState.hs
hledger/Hledger/Cli/Commands/Close.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/test/journal/transaction-prices.test

they can be matched by queries.

fix: cost: Add inferred equity postings during journal finalisation, so

---

hledger-lib/Hledger/Read/Common.hs
hledger/test/check-accounts.test

fix: strict: Make sure forecast transactions and auto postings are checked with --strict

---

hledger-lib/Hledger/Data/Balancing.hs
hledger-lib/Hledger/Read/Common.hs
hledger-lib/Hledger/Utils/Parse.hs
hledger/Hledger/Cli/Commands/Check/Ordereddates.hs
hledger/Hledger/Cli/Commands/Check/Uniqueleafnames.hs
hledger/test/journal/balance-assertions.test
hledger/test/journal/parse-errors.test

Change showSourcePos to sourcePosPretty, and showSourcePosPair to
sourcePosPairPretty.

cln!: sourcepos: Use megaparsec-supplied sourcePosPretty.

---

hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/Hledger/Cli/Utils.hs

When rendering register or aregister reports, calculate the amount /
balance width based on the first 100 items, and start rendering in that
way. If you encounter a longer one, update and continue rendering. This
will result in adjustment of column width for long reports, but allows
us to save a lot more performant/efficient.
We also only render each amount once, rather than twice as before, by
storing the rendered amount in a tuple.

dev: reg: areg: Be more clever about register and aregister alignment.

---

bin/hledger-check-fancyassertions.hs
hledger-lib/Hledger/Read.hs
hledger-lib/Hledger/Read/CsvReader.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
hledger-web/Hledger/Web/Foundation.hs
hledger-web/Hledger/Web/Handler/EditR.hs
hledger-web/Hledger/Web/Handler/UploadR.hs
hledger-web/Hledger/Web/Test.hs
hledger-web/Hledger/Web/Widget/Common.hs
hledger/Hledger/Cli/Commands.hs
hledger/Hledger/Cli/Commands/Diff.hs
hledger/Hledger/Cli/Commands/Import.hs
hledger/Hledger/Cli/Utils.hs
hledger/test/csv.test

This increases composability and avoids some ugly case handling.

ref: Use ExceptT String IO a instead of IO (Either String a).

---

hledger/shell-completion/hledger-completion.bash

I updated the completions for hledger 1.25.99
As far as I remember, the completions are already generated and packaged automatically but we once decided to also commit it into the repo so that the completion file can be downloaded and installed manually.

Update bash completions

---

README.md

Corrected the extension for the CREDITS file.

CREDITS.html -> CREDITS.md

---

examples/csv/capital-one.csv.rules

hey there! hledger newbie here and just wanted to share some rules for .csv import for a financial institution that's popular in the US.
it also serves as an example of how to set posting dates given secondary dates from .csvs.
let me know if i can change anything, or if it doesn't belong :)
thank you all so much for this project!!

examples/csv: add example for capital one credit cards [ci skip]

---

ACHIEVEMENTS.md

noticed these when digging thru the docs!

Update achievements listing

---

bin/README.md

Fix broken link in bin/README.md

---

hledger-lib/Hledger/Reports/ReportOptions.hs
hledger-ui/Hledger/UI/AccountsScreen.hs
hledger-ui/Hledger/UI/ErrorScreen.hs
hledger-ui/Hledger/UI/Main.hs
hledger-ui/Hledger/UI/RegisterScreen.hs
hledger-ui/Hledger/UI/TransactionScreen.hs
hledger-ui/Hledger/UI/UIScreens.hs
hledger-ui/Hledger/UI/UIState.hs
hledger-ui/Hledger/UI/UITypes.hs
hledger-ui/Hledger/UI/UIUtils.hs
hledger-ui/hledger-ui.cabal

- dev: lib: improve ReportSpec doc
- dev: ui: refactor: simpler, more debuggable Screen type

ui: simpler, more debuggable Screen type

---

hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger-ui/hledger-ui.cabal
hledger-ui/package.yaml
hledger-web/hledger-web.cabal
hledger-web/package.yaml
hledger/hledger.cabal
hledger/package.yaml

Builds fine and all tests pass.

Allow megaparsec 9.3

---

hledger/Hledger/Cli/Commands/Roi.md

Clean up docs a bit after PR #2069

;doc:roi: mention annualization differences, clean up TWR section

---

examples/csv/ING.rules
examples/csv/Venmo.rules
examples/csv/Wise.rules
examples/csv/first-hawaiian-bank.rules
examples/csv/n26-main.rules
examples/csv/paypal-2023.rules
examples/csv/triodos.rules

;add more CSV parsing rule files

---

hledger-ui/Hledger/UI/Theme.hs
hledger-ui/hledger-ui.1
hledger-ui/hledger-ui.info
hledger-ui/hledger-ui.m4.md
hledger-ui/hledger-ui.txt

I wanted a theme with roughly the same degree of colour as the default but which was easier on my eyes late at night.
(Also; I wanted to build hledger on my new machine to get back to #2158, and this was an itch to scratch)

feat: ui: Add a dark theme

---

hledger/Hledger/Cli/Commands/Balance.hs

bugfix for a duplicate transposition in Commands.Balance.budgetReport

Budget transpose

---

.github/workflows/binaries-linux-arm32v7.yml
.github/workflows/binaries-linux-x64-stack.yml
.github/workflows/binaries-linux-x64.yml
.github/workflows/binaries-mac-arm64.yml
.github/workflows/binaries-mac-x64.yml
.github/workflows/binaries-windows-x64.yml

From a cursory check, this appears to be what's needed, but I may be mistaken.
Would appreciate a review
Closes: #986

Add bash completion to bindist

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs

compoundBalanceReportAsHtml: create according TH cells only if row-total or average is requested

---

hledger-web/static/hledger.js
hledger-web/templates/add-form.hamlet

A fix for #2215, autocomplete in account fields 5 and beyond, that's having no effect - maybe someone else can see why ?

web: fix #2215 autocomplete in dynamically added account fields

---

hledger/Hledger/Cli/CompoundBalanceCommand.hs

a minor addition to 6ce6c72fd42b656bcec90a27f59a9884da83b103

cli: CompoundBalanceCommand: use Html.Attribute.alignleft

---

hledger-lib/Hledger/Write/Html.hs
hledger-lib/Hledger/Write/Html/Attribute.hs
hledger-lib/Hledger/Write/Html/Blaze.hs
hledger-lib/Hledger/Write/Html/Lucid.hs
hledger-lib/hledger-lib.cabal
hledger-lib/package.yaml
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

Add another Html backend, for compatibility with hledger-web.
Please merge before the cell-merge and hledger-web commits.
The pull request subsumes https://github.com/simonmichael/hledger/pull/2243.

Write.Html.Blaze

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/test/balance/balance.test
hledger/test/balance/drop.test

A proposal to fix https://github.com/simonmichael/hledger/issues/1846

Spreadsheet tree mode

---

hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

this should fix https://github.com/simonmichael/hledger/issues/2251

cli: CompoundBalanceCommand: row_total_ -> multiBalanceHasTotalsColumn

---

hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Commands/Balance.hs
hledger/Hledger/Cli/CompoundBalanceCommand.hs

This prepares new bare-wide layout and FODS export for CompoundBalance.

Some refactoring to HTML/Spreadsheet export of balance reports

---

hledger-ui/Hledger/UI/Editor.hs

feat(hledger-ui): add helix as a supported editor

---

hledger-lib/Hledger/Write/Spreadsheet.hs
hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Print.hs
hledger/Hledger/Cli/Commands/Register.hs
hledger/hledger.m4.md

This completes the matrix of output formats with respect to HTML and FODS.

Aregister export to FODS

---

hledger/Hledger/Cli/Commands/Aregister.hs
hledger/Hledger/Cli/Commands/Aregister.md

Resolves this issue:
https://github.com/simonmichael/hledger/pull/2274#issuecomment-2449003007

cli: Commands.Aregister: --header -> --heading

---

Justfile
bench-10ktxns-100kaccts.sh
bench-10ktxns-10kaccts.sh
bench.sh
bench100k.sh
bench10k.sh
bench1k.sh
bench5k.sh
hledger/bench/bench.hs

* Make `bench/bench.hs` compileable.
* Update `bench*.sh` files to reflect changes in output of `just samplefiles`.
See commit messages for more details.

Fix bench files

---

hledger/Hledger/Cli/Commands/Repl.txt

Corrected one small mistake, and changed a few other things for clarity.

;doc:repl: updates

---

README.md

;docs:README.md

---

hledger-lib/Hledger/Read/RulesReader.hs
hledger/test/csv.test

fix: csv: fix regression in parsing rules containing & (#2352)

---

.github/FUNDING.yml

;doc: FUNDING.yml: hide patreon for now

---

hledger-lib/Hledger/Read/Common.hs

Fix: "balanced" check is enabled only with "check" command
